function Strings( config ) {

	const language = config.getKey( 'language' );

	const values = {
		en: {
			'menubar/file': 'File',
			'menubar/file/new': 'New',
			'menubar/file/import': 'Import',
			'menubar/file/save': 'Save',
			'menubar/file/export/geometry': 'Export Geometry',
			'menubar/file/export/object': 'Export Object',
			'menubar/file/export/scene': 'Export Scene',
			'menubar/file/export/dae': 'Export DAE',
			'menubar/file/export/drc': 'Export DRC',
			'menubar/file/export/glb': 'Export GLB',
			'menubar/file/export/gltf': 'Export GLTF',
			'menubar/file/export/obj': 'Export OBJ',
			'menubar/file/export/ply': 'Export PLY',
			'menubar/file/export/ply_binary': 'Export PLY (Binary)',
			'menubar/file/export/stl': 'Export STL',
			'menubar/file/export/stl_binary': 'Export STL (Binary)',
			'menubar/file/export/usdz': 'Export USDZ',
			'menubar/file/publish': 'Publish',

			'menubar/edit': 'Edit',
			'menubar/edit/undo': 'Undo (Ctrl+Z)',
			'menubar/edit/redo': 'Redo (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': 'Clear History',
			'menubar/edit/center': 'Center',
			'menubar/edit/clone': 'Clone',
			'menubar/edit/delete': 'Delete (Del)',
			'menubar/edit/fixcolormaps': 'Fix Color Maps',

			'menubar/add': 'Add',
			'menubar/add/node': 'Node',
			'menubar/add/text': 'Text',
			'menubar/add/voxel': 'Voxel',
			'menubar/add/phototype': 'Phototype',
			'menubar/add/polygen': 'Polygen',
			'menubar/add/audio': 'Audio',
			'menubar/add/picture': 'Picture',
			'menubar/add/video': 'Video',
			'menubar/add/particle': 'Particle',
			'menubar/add/meta': 'Point',
			'menubar/add/prefab': 'Prefab',
			'menubar/add/group': 'Group',
			'menubar/add/plane': 'Plane',
			'menubar/add/box': 'Box',
			'menubar/add/capsule': 'Capsule',
			'menubar/add/circle': 'Circle',
			'menubar/add/cylinder': 'Cylinder',
			'menubar/add/ring': 'Ring',
			'menubar/add/sphere': 'Sphere',
			'menubar/add/dodecahedron': 'Dodecahedron',
			'menubar/add/icosahedron': 'Icosahedron',
			'menubar/add/octahedron': 'Octahedron',
			'menubar/add/tetrahedron': 'Tetrahedron',
			'menubar/add/torus': 'Torus',
			'menubar/add/tube': 'Tube',
			'menubar/add/torusknot': 'TorusKnot',
			'menubar/add/lathe': 'Lathe',
			'menubar/add/sprite': 'Sprite',
			'menubar/add/pointlight': 'PointLight',
			'menubar/add/spotlight': 'SpotLight',
			'menubar/add/directionallight': 'DirectionalLight',
			'menubar/add/hemispherelight': 'HemisphereLight',
			'menubar/add/ambientlight': 'AmbientLight',
			'menubar/add/perspectivecamera': 'PerspectiveCamera',
			'menubar/add/orthographiccamera': 'OrthographicCamera',

			'menubar/replace': 'Replace',
			'menubar/replace/polygen': 'Polygen',
			'menubar/replace/voxel': 'Voxel',
			'menubar/replace/picture': 'Picture',
			'menubar/replace/noselection': 'Please select an object first',
			'menubar/replace/success': 'Successfully replaced object',
			'menubar/component': 'Component',
			'menubar/component/list': 'View Components',

			'menubar/command': 'Command',
			'menubar/command/list': 'View Commands',
			'menubar/command/confirm': 'Do you want to add the "{0}" command to the current object?',
			'menubar/command/success': 'Successfully added "{0}" command',
			'menubar/command/select_object_first': 'Please select an object first',
			'menubar/command/already_exists': 'This object already has a voice command, you cannot add another one',

			'menubar/code': 'Code',
			'menubar/code/script': 'Script Edit',

			'menubar/status/autosave': 'autosave',

			'menubar/play': 'Play',
			'menubar/play/stop': 'Stop',
			'menubar/play/play': 'Play',

			'menubar/examples': 'Examples',
			'menubar/examples/Arkanoid': 'Arkanoid',
			'menubar/examples/Camera': 'Camera',
			'menubar/examples/Particles': 'Particles',
			'menubar/examples/Pong': 'Pong',
			'menubar/examples/Shaders': 'Shaders',

			'menubar/view': 'View',
			'menubar/view/fullscreen': 'Fullscreen',

			'menubar/help': 'Help',
			'menubar/help/source_code': 'Source Code',
			'menubar/help/icons': 'Icon Pack',
			'menubar/help/about': 'About',
			'menubar/help/manual': 'Manual',

			'sidebar/animations': 'Animations',
			'sidebar/animations/play': 'Play',
			'sidebar/animations/stop': 'Stop',
			'sidebar/animations/timescale': 'Time Scale',
			'sidebar/animations/select': 'Select',

			'sidebar/scene': 'Scene',
			'sidebar/scene/background': 'Background',
			'sidebar/scene/environment': 'Environment',
			'sidebar/scene/fog': 'Fog',

			'sidebar/properties/object': 'Object',
			'sidebar/properties/geometry': 'Geometry',
			'sidebar/properties/material': 'Material',
			'sidebar/properties/script': 'Script',

			'sidebar/object/type': 'Type',
			'sidebar/object/new': 'New',
			'sidebar/object/uuid': 'UUID',
			'sidebar/object/name': 'Name',
			'sidebar/object/position': 'Position',
			'sidebar/object/rotation': 'Rotation',
			'sidebar/object/isRotating': 'Rotate on Start',
			'sidebar/object/scale': 'Scale',
			'sidebar/object/fov': 'Fov',
			'sidebar/object/left': 'Left',
			'sidebar/object/right': 'Right',
			'sidebar/object/top': 'Top',
			'sidebar/object/bottom': 'Bottom',
			'sidebar/object/near': 'Near',
			'sidebar/object/far': 'Far',
			'sidebar/object/intensity': 'Intensity',
			'sidebar/object/color': 'Color',
			'sidebar/object/groundcolor': 'Ground Color',
			'sidebar/object/distance': 'Distance',
			'sidebar/object/angle': 'Angle',
			'sidebar/object/penumbra': 'Penumbra',
			'sidebar/object/decay': 'Decay',
			'sidebar/object/shadow': 'Shadow',
			'sidebar/object/shadowBias': 'Shadow Bias',
			'sidebar/object/shadowNormalBias': 'Shadow Normal Bias',
			'sidebar/object/shadowRadius': 'Shadow Radius',
			'sidebar/object/cast': 'cast',
			'sidebar/object/receive': 'receive',
			'sidebar/object/visible': 'Visible',
			'sidebar/object/loop': 'Loop playback',
			'sidebar/object/frustumcull': 'Frustum Cull',
			'sidebar/object/renderorder': 'Render Order',
			'sidebar/object/text': 'Text Content',
			'sidebar/object/userdata': 'User data',

			'sidebar/components': 'Components',
			'sidebar/components/select': 'Select',
			'sidebar/components/select/rotate': 'Rotate',
			'sidebar/components/select/action': 'Click Action',
			'sidebar/components/select/moved': 'Movable',
			'sidebar/components/select/trigger': 'Collision Trigger',
			'sidebar/components/select/button': 'New',
			'sidebar/components/select/tooltip': 'Label',
			'sidebar/components/remove/confirm': 'Are you sure you want to delete this component?',
			'sidebar/components/tooltip/text': 'Text',
			'sidebar/components/tooltip/length': 'Length',
			'sidebar/components/tooltip/target': 'Target Position',
			'sidebar/command': 'Command',
			'sidebar/command/select': 'Select',
			'sidebar/command/select/voice': 'Voice Command',
			'sidebar/command/select/button': 'New',
			'sidebar/command/remove': 'Remove',
			'sidebar/command/remove/confirm': 'Are you sure you want to delete this command?',
			'sidebar/command/voice/id': 'ID',
			'sidebar/command/voice/label': 'Voice',
			'sidebar/command/voice/scaleUp': 'Scale Up',
			'sidebar/command/voice/scaleDown': 'Scale Down',
			'sidebar/command/voice/decompose': 'Decompose',
			'sidebar/command/voice/reset': 'Reset',
			'sidebar/command/voice/nextStep': 'Next Step',
			'sidebar/command/voice/returnMain': 'Return Main Menu',
			'sidebar/command/voice/closeTooltip': 'Close Tooltip',
			'sidebar/command/voice/openTooltip': 'Open Tooltip',
			'sidebar/command/voice/vertical': 'Vertical',
			'sidebar/command/voice/horizontal': 'Horizontal',
			'sidebar/command/voice/hidden': 'Hidden',
			'sidebar/command/voice/visible': 'Visible',
			'sidebar/command/voice/showYuelu': 'Show Yuelu Campus',
			'sidebar/command/voice/showLunan': 'Show Lunan Campus',
			'sidebar/command/voice/showXiaoxiang': 'Show Xiaoxiang Campus',
			'sidebar/command/voice/showTianxin': 'Show Tianxin Campus',
			'sidebar/command/voice/showXinglin': 'Show Xinglin Campus',
			'sidebar/command/voice/showKaifu': 'Show Kaifu Campus',
			'sidebar/command/voice/goBack': 'Go Back',
			'sidebar/command/voice/bgmOn': 'Play Background Music',
			'sidebar/command/voice/bgmOff': 'Stop Background Music',
			'sidebar/command/voice/sandboxFxOn': 'Enable Sandbox Effects',
			'sidebar/command/voice/sandboxFxOff': 'Disable Sandbox Effects',

			'sidebar/entity': 'Point(Custom)',
			'sidebar/entity/button': 'Edit',

			'sidebar/confirm/scene/modified': 'The scene has been modified, whether to save?',

			'sidebar/geometry/type': 'Type',
			'sidebar/geometry/new': 'New',
			'sidebar/geometry/uuid': 'UUID',
			'sidebar/geometry/name': 'Name',
			'sidebar/geometry/bounds': 'Bounds',
			'sidebar/geometry/show_vertex_normals': 'Show Vertex Normals',

			'sidebar/geometry/box_geometry/width': 'Width',
			'sidebar/geometry/box_geometry/height': 'Height',
			'sidebar/geometry/box_geometry/depth': 'Depth',
			'sidebar/geometry/box_geometry/widthseg': 'Width Seg',
			'sidebar/geometry/box_geometry/heightseg': 'Height Seg',
			'sidebar/geometry/box_geometry/depthseg': 'Depth Seg',

			'sidebar/geometry/buffer_geometry/attributes': 'Attributes',
			'sidebar/geometry/buffer_geometry/index': 'index',

			'sidebar/geometry/capsule_geometry/radius': 'Radius',
			'sidebar/geometry/capsule_geometry/length': 'Length',
			'sidebar/geometry/capsule_geometry/capseg': 'Cap Seg',
			'sidebar/geometry/capsule_geometry/radialseg': 'Radial Seg',

			'sidebar/geometry/circle_geometry/radius': 'Radius',
			'sidebar/geometry/circle_geometry/segments': 'Segments',
			'sidebar/geometry/circle_geometry/thetastart': 'Theta start',
			'sidebar/geometry/circle_geometry/thetalength': 'Theta length',

			'sidebar/geometry/cylinder_geometry/radiustop': 'Radius top',
			'sidebar/geometry/cylinder_geometry/radiusbottom': 'Radius bottom',
			'sidebar/geometry/cylinder_geometry/height': 'Height',
			'sidebar/geometry/cylinder_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/cylinder_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/cylinder_geometry/openended': 'Open ended',

			'sidebar/geometry/extrude_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/extrude_geometry/steps': 'Steps',
			'sidebar/geometry/extrude_geometry/depth': 'Depth',
			'sidebar/geometry/extrude_geometry/bevelEnabled': 'Bevel?',
			'sidebar/geometry/extrude_geometry/bevelThickness': 'Thickness',
			'sidebar/geometry/extrude_geometry/bevelSize': 'Size',
			'sidebar/geometry/extrude_geometry/bevelOffset': 'Offset',
			'sidebar/geometry/extrude_geometry/bevelSegments': 'Segments',
			'sidebar/geometry/extrude_geometry/shape': 'Convert to Shape',

			'sidebar/geometry/dodecahedron_geometry/radius': 'Radius',
			'sidebar/geometry/dodecahedron_geometry/detail': 'Detail',

			'sidebar/geometry/icosahedron_geometry/radius': 'Radius',
			'sidebar/geometry/icosahedron_geometry/detail': 'Detail',

			'sidebar/geometry/octahedron_geometry/radius': 'Radius',
			'sidebar/geometry/octahedron_geometry/detail': 'Detail',

			'sidebar/geometry/tetrahedron_geometry/radius': 'Radius',
			'sidebar/geometry/tetrahedron_geometry/detail': 'Detail',

			'sidebar/geometry/lathe_geometry/segments': 'Segments',
			'sidebar/geometry/lathe_geometry/phistart': 'Phi start (°)',
			'sidebar/geometry/lathe_geometry/philength': 'Phi length (°)',
			'sidebar/geometry/lathe_geometry/points': 'Points',

			'sidebar/geometry/plane_geometry/width': 'Width',
			'sidebar/geometry/plane_geometry/height': 'Height',
			'sidebar/geometry/plane_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/plane_geometry/heightsegments': 'Height segments',

			'sidebar/geometry/ring_geometry/innerRadius': 'Inner radius',
			'sidebar/geometry/ring_geometry/outerRadius': 'Outer radius',
			'sidebar/geometry/ring_geometry/thetaSegments': 'Theta segments',
			'sidebar/geometry/ring_geometry/phiSegments': 'Phi segments',
			'sidebar/geometry/ring_geometry/thetastart': 'Theta start',
			'sidebar/geometry/ring_geometry/thetalength': 'Theta length',

			'sidebar/geometry/shape_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/shape_geometry/extrude': 'Extrude',

			'sidebar/geometry/sphere_geometry/radius': 'Radius',
			'sidebar/geometry/sphere_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/sphere_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/sphere_geometry/phistart': 'Phi start',
			'sidebar/geometry/sphere_geometry/philength': 'Phi length',
			'sidebar/geometry/sphere_geometry/thetastart': 'Theta start',
			'sidebar/geometry/sphere_geometry/thetalength': 'Theta length',

			'sidebar/geometry/torus_geometry/radius': 'Radius',
			'sidebar/geometry/torus_geometry/tube': 'Tube',
			'sidebar/geometry/torus_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torus_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torus_geometry/arc': 'Arc',

			'sidebar/geometry/torusKnot_geometry/radius': 'Radius',
			'sidebar/geometry/torusKnot_geometry/tube': 'Tube',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torusKnot_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torusKnot_geometry/p': 'P',
			'sidebar/geometry/torusKnot_geometry/q': 'Q',

			'sidebar/geometry/tube_geometry/path': 'Path',
			'sidebar/geometry/tube_geometry/radius': 'Radius',
			'sidebar/geometry/tube_geometry/tube': 'Tube',
			'sidebar/geometry/tube_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/tube_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/tube_geometry/closed': 'Closed',
			'sidebar/geometry/tube_geometry/curvetype': 'Curve Type',
			'sidebar/geometry/tube_geometry/tension': 'Tension',

			'sidebar/material/new': 'New',
			'sidebar/material/copy': 'Copy',
			'sidebar/material/paste': 'Paste',
			'sidebar/material/slot': 'Slot',
			'sidebar/material/type': 'Type',
			'sidebar/material/uuid': 'UUID',
			'sidebar/material/name': 'Name',
			'sidebar/material/program': 'Program',
			'sidebar/material/info': 'Info',
			'sidebar/material/vertex': 'Vert',
			'sidebar/material/fragment': 'Frag',
			'sidebar/material/color': 'Color',
			'sidebar/material/depthPacking': 'Depth Packing',
			'sidebar/material/roughness': 'Roughness',
			'sidebar/material/metalness': 'Metalness',
			'sidebar/material/reflectivity': 'Reflectivity',
			'sidebar/material/emissive': 'Emissive',
			'sidebar/material/specular': 'Specular',
			'sidebar/material/shininess': 'Shininess',
			'sidebar/material/clearcoat': 'Clearcoat',
			'sidebar/material/clearcoatroughness': 'Clearcoat Roughness',
			'sidebar/material/transmission': 'Transmission',
			'sidebar/material/attenuationDistance': 'Attenuation Distance',
			'sidebar/material/attenuationColor': 'Attenuation Color',
			'sidebar/material/thickness': 'Thickness',
			'sidebar/material/vertexcolors': 'Vertex Colors',
			'sidebar/material/matcap': 'Matcap',
			'sidebar/material/map': 'Map',
			'sidebar/material/alphamap': 'Alpha Map',
			'sidebar/material/bumpmap': 'Bump Map',
			'sidebar/material/normalmap': 'Normal Map',
			'sidebar/material/clearcoatnormalmap': 'Clearcoat Normal Map',
			'sidebar/material/displacementmap': 'Displace Map',
			'sidebar/material/roughnessmap': 'Rough. Map',
			'sidebar/material/metalnessmap': 'Metal. Map',
			'sidebar/material/specularmap': 'Specular Map',
			'sidebar/material/envmap': 'Env Map',
			'sidebar/material/lightmap': 'Light Map',
			'sidebar/material/aomap': 'AO Map',
			'sidebar/material/emissivemap': 'Emissive Map',
			'sidebar/material/gradientmap': 'Gradient Map',
			'sidebar/material/side': 'Side',
			'sidebar/material/size': 'Size',
			'sidebar/material/sizeAttenuation': 'Size Attenuation',
			'sidebar/material/flatShading': 'Flat Shading',
			'sidebar/material/blending': 'Blending',
			'sidebar/material/opacity': 'Opacity',
			'sidebar/material/transparent': 'Transparent',
			'sidebar/material/alphatest': 'Alpha Test',
			'sidebar/material/depthtest': 'Depth Test',
			'sidebar/material/depthwrite': 'Depth Write',
			'sidebar/material/wireframe': 'Wireframe',
			'sidebar/material/userdata': 'User data',

			'sidebar/script': 'Script',
			'sidebar/script/new': 'New',
			'sidebar/script/edit': 'Edit',
			'sidebar/script/remove': 'Remove',

			'sidebar/project': 'Project',
			'sidebar/project/title': 'Title',
			'sidebar/project/editable': 'Editable',
			'sidebar/project/vr': 'VR',
			'sidebar/project/renderer': 'Renderer',
			'sidebar/project/antialias': 'Antialias',
			'sidebar/project/shadows': 'Shadows',
			'sidebar/project/physicallyCorrectLights': 'Physical lights',
			'sidebar/project/toneMapping': 'Tone mapping',
			'sidebar/project/materials': 'Materials',
			'sidebar/project/Assign': 'Assign',

			'sidebar/project/video': 'Video',
			'sidebar/project/resolution': 'Resolution',
			'sidebar/project/duration': 'Duration',
			'sidebar/project/render': 'Render',

			'sidebar/settings': 'Settings',
			'sidebar/settings/language': 'Language',

			'sidebar/settings/shortcuts': 'Shortcuts',
			'sidebar/settings/shortcuts/translate': 'Translate',
			'sidebar/settings/shortcuts/rotate': 'Rotate',
			'sidebar/settings/shortcuts/scale': 'Scale',
			'sidebar/settings/shortcuts/undo': 'Undo',
			'sidebar/settings/shortcuts/focus': 'Focus',
			'sidebar/settings/shortcuts/save': 'Save',

			'sidebar/settings/viewport': 'Viewport',
			'sidebar/settings/viewport/grid': 'Grid',
			'sidebar/settings/viewport/helpers': 'Helpers',

			'sidebar/history': 'History',
			'sidebar/history/persistent': 'persistent',

			'toolbar/translate': 'Translate',
			'toolbar/rotate': 'Rotate',
			'toolbar/scale': 'Scale',
			'toolbar/local': 'Local',

			'viewport/info/objects': 'Objects',
			'viewport/info/vertices': 'Vertices',
			'viewport/info/triangles': 'Triangles',
			'viewport/info/frametime': 'Frametime',
			'sidebar/screenshot': 'Screenshot',
			'sidebar/screenshot/resolution': 'Resolution',
			'sidebar/screenshot/resolution/current': 'Current Viewport',
			'sidebar/screenshot/background': 'Background',
			'sidebar/screenshot/background/original': 'Original',
			'sidebar/screenshot/background/white': 'White',
			'sidebar/screenshot/background/light': 'Light',
			'sidebar/screenshot/background/dark': 'Dark',
			'sidebar/screenshot/background/black': 'Black',
			'sidebar/screenshot/filename': 'Filename',
			'sidebar/screenshot/format': 'Format',
			'sidebar/screenshot/capture': 'Capture Screenshot',
			'sidebar/screenshot/preview': 'Preview',
			'sidebar/screenshot/download': 'Download Image',
			'sidebar/screenshot/uploadAsCover': 'Upload as Cover',

			'menubar/screenshot': 'Screenshot',
			'menubar/screenshot/capture': 'Capture Screenshot',
			'menubar/screenshot/confirm_upload': 'Screenshot captured successfully! Do you want to upload it as cover?',
			'menubar/screenshot/uploading': 'Uploading cover...',
			'menubar/screenshot/upload_canceled': 'Upload canceled',
			'menubar/screenshot/error/viewport_not_found': 'Cannot find viewport element',
			'menubar/screenshot/error/canvas_not_found': 'Cannot find renderer canvas',
			'menubar/screenshot/error/capture_failed': 'Screenshot failed',
			'menubar/screenshot/download': 'Download',
			'menubar/screenshot/downloaded': 'Downloaded: ',
			'menubar/screenshot/upload': 'Upload as cover',
			'menubar/screenshot/cancel': 'Cancel',

			'menubar/component/confirm': 'Do you want to add the "{0}" component to the current object?',
			'menubar/component/success': 'Successfully added "{0}" component',
			'menubar/component/select_object_first': 'Please select an object first',

			'menubar/command/confirm': 'Do you want to add the "{0}" command to the current object?',
			'menubar/command/success': 'Successfully added "{0}" command',
			'menubar/command/select_object_first': 'Please select an object first',
			'menubar/command/already_exists': 'This object already has a voice command, you cannot add another one',
			'menubar/component/mutually_exclusive': 'Only one of these components can be selected: Click Action, Movable or Collision Trigger',

			'sidebar/media': 'Media Control',
			'sidebar/media/play': 'Play',
			'sidebar/media/pause': 'Pause',
			'sidebar/media/time': 'Time',
			'sidebar/media/volume': 'Volume',
			'sidebar/media/speed': 'Speed',
			'sidebar/media/loop': 'Loop',
			'sidebar/media/muted': 'Muted'
		},



		zh: {
			'menubar/file': '文件~',
			'menubar/file/new': '新建',
			'menubar/file/import': '导入',
			'menubar/file/save': '保存',
			'menubar/file/export/geometry': '导出几何体',
			'menubar/file/export/object': '导出物体',
			'menubar/file/export/scene': '导出场景',
			'menubar/file/export/dae': '导出DAE',
			'menubar/file/export/drc': '导出DRC',
			'menubar/file/export/glb': '导出GLB',
			'menubar/file/export/gltf': '导出GLTF',
			'menubar/file/export/obj': '导出OBJ',
			'menubar/file/export/ply': '导出PLY',
			'menubar/file/export/ply_binary': '导出PLY(二进制)',
			'menubar/file/export/stl': '导出STL',
			'menubar/file/export/stl_binary': '导出STL(二进制)',
			'menubar/file/export/usdz': '导出USDZ',
			'menubar/file/publish': '发布',

			'menubar/edit': '编辑',
			'menubar/edit/undo': '撤销 (Ctrl+Z)',
			'menubar/edit/redo': '重做 (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': '清空历史记录',
			'menubar/edit/center': '居中',
			'menubar/edit/clone': '拷贝',
			'menubar/edit/delete': '删除 (Del)',
			'menubar/edit/fixcolormaps': '修复颜色贴图',

			'menubar/add': '添加',
			'menubar/add/node': '节点',
			'menubar/add/text': '文本',
			'menubar/add/voxel': '体素',
			'menubar/add/phototype': 'Phototype',
			'menubar/add/phototype': '原型',
			'menubar/add/polygen': '模型',
			'menubar/add/audio': '音频',
			'menubar/add/picture': '图片',
			'menubar/add/video': '视频',
			'menubar/add/particle': '特效',
			'menubar/add/meta': '实体',
			'menubar/add/prefab': '预设',
			'menubar/add/group': '组',
			'menubar/add/plane': '平面',
			'menubar/add/box': '正方体',
			'menubar/add/capsule': '胶囊',
			'menubar/add/circle': '圆',
			'menubar/add/cylinder': '圆柱体',
			'menubar/add/ring': '环',
			'menubar/add/sphere': '球体',
			'menubar/add/dodecahedron': '十二面体',
			'menubar/add/icosahedron': '二十面体',
			'menubar/add/octahedron': '八面体',
			'menubar/add/tetrahedron': '四面体',
			'menubar/add/torus': '圆环体',
			'menubar/add/torusknot': '环面纽结体',
			'menubar/add/tube': '管',
			'menubar/add/lathe': '酒杯',
			'menubar/add/sprite': '精灵',
			'menubar/add/pointlight': '点光源',
			'menubar/add/spotlight': '聚光灯',
			'menubar/add/directionallight': '平行光',
			'menubar/add/hemispherelight': '半球光',
			'menubar/add/ambientlight': '环境光',
			'menubar/add/perspectivecamera': '透视相机',
			'menubar/add/orthographiccamera': '正交相机',

			'menubar/replace': '替换',
			'menubar/replace/polygen': '模型',
			'menubar/replace/voxel': '体素',
			'menubar/replace/picture': '图片',
			'menubar/replace/noselection': '请先选择一个对象',
			'menubar/replace/success': '替换成功',
			'menubar/component': '组件',
			'menubar/component/list': '查看组件',
			'menubar/component/confirm': '确定要为当前对象添加 "{0}" 组件吗？',
			'menubar/component/success': '已成功添加 "{0}" 组件',
			'menubar/component/select_object_first': '请先选择一个对象',

			'menubar/command': '指令',
			'menubar/command/list': '查看指令',
			'menubar/command/confirm': '确定要为当前对象添加 "{0}" 指令吗？',
			'menubar/command/success': '已成功添加 "{0}" 指令',
			'menubar/command/select_object_first': '请先选择一个对象',
			'menubar/command/already_exists': '此对象已添加语音指令，不能重复添加',

			'menubar/code': '脚本',
			'menubar/code/script': '脚本编辑',

			'menubar/status/autosave': '自动保存',

			'menubar/play': '启动',
			'menubar/play/stop': '暂停',
			'menubar/play/play': '启动',

			'menubar/examples': '示例',
			'menubar/examples/Arkanoid': '打砖块',
			'menubar/examples/Camera': ' 摄像机',
			'menubar/examples/Particles': '粒子',
			'menubar/examples/Pong': '乒乓球',
			'menubar/examples/Shaders': '着色器',

			'menubar/view': '视图',
			'menubar/view/fullscreen': '全屏',

			'menubar/help': '帮助',
			'menubar/help/source_code': '源码',
			'menubar/help/icons': '图标组件包',
			'menubar/help/about': '关于',
			'menubar/help/manual': '手册',

			'sidebar/animations': '动画',
			'sidebar/animations/play': '播放',
			'sidebar/animations/stop': '暂停',
			'sidebar/animations/timescale': '时间缩放',
			'sidebar/animations/select': '选择项',

			'sidebar/scene': '场景',
			'sidebar/scene/background': '背景',
			'sidebar/scene/environment': '环境',
			'sidebar/scene/fog': '雾',

			'sidebar/properties/object': '属性',
			'sidebar/properties/geometry': '几何组件',
			'sidebar/properties/material': '材质组件',
			'sidebar/properties/script': '脚本',

			'sidebar/object/type': '类型',
			'sidebar/object/new': '更新',
			'sidebar/object/uuid': '识别码',
			'sidebar/object/name': '名称',
			'sidebar/object/position': '位置',
			'sidebar/object/rotation': '旋转',
			'sidebar/object/isRotating': '启动时旋转',
			'sidebar/object/scale': '缩放',
			'sidebar/object/fov': '视角',
			'sidebar/object/left': '左',
			'sidebar/object/right': '右',
			'sidebar/object/top': '上',
			'sidebar/object/bottom': '下',
			'sidebar/object/near': '近点',
			'sidebar/object/far': '远点',
			'sidebar/object/intensity': '强度',
			'sidebar/object/color': '颜色',
			'sidebar/object/groundcolor': '基色',
			'sidebar/object/distance': '距离',
			'sidebar/object/angle': '角度',
			'sidebar/object/penumbra': '边缘',
			'sidebar/object/decay': '衰减',
			'sidebar/object/shadow': '阴影',
			'sidebar/object/shadowBias': '阴影偏移',
			'sidebar/object/shadowNormalBias': '阴影法线偏移',
			'sidebar/object/shadowRadius': '阴影半径',
			'sidebar/object/cast': '产生',
			'sidebar/object/receive': '接受',
			'sidebar/object/visible': '可见性',
			'sidebar/object/loop': '循环播放',
			'sidebar/object/frustumcull': '视锥体裁剪',
			'sidebar/object/renderorder': '渲染次序',
			'sidebar/object/text': '文本内容',
			'sidebar/object/userdata': '自定义数据',

			'sidebar/components': '组件',
			'sidebar/components/select': '选择项',
			'sidebar/components/select/rotate': '自旋转',
			'sidebar/components/select/action': '点击触发',
			'sidebar/components/select/moved': '可移动',
			'sidebar/components/select/trigger': '碰撞触发',
			'sidebar/components/select/button': '新建',
			'sidebar/components/select/tooltip': '标签',
			'sidebar/components/remove/confirm': '确定要删除这个组件吗？',
			'sidebar/components/tooltip/text': '文本',
			'sidebar/components/tooltip/length': '长度',
			'sidebar/components/tooltip/target': '目标位置',
			'sidebar/command': '指令',
			'sidebar/command/select': '选择项',
			'sidebar/command/select/voice': '语音指令',
			'sidebar/command/select/button': '新建',
			'sidebar/command/remove': '删除',
			'sidebar/command/remove/confirm': '确定要删除这个指令吗？',
			'sidebar/command/voice/id': '识别码',
			'sidebar/command/voice/label': '语音',
			'sidebar/command/voice/scaleUp': '放大',
			'sidebar/command/voice/scaleDown': '缩小',
			'sidebar/command/voice/decompose': '分解',
			'sidebar/command/voice/reset': '还原',
			'sidebar/command/voice/nextStep': '下一步',
			'sidebar/command/voice/returnMain': '返回主界面',
			'sidebar/command/voice/closeTooltip': '关闭说明卡',
			'sidebar/command/voice/openTooltip': '显示说明卡',
			'sidebar/command/voice/vertical': '垂直展示',
			'sidebar/command/voice/horizontal': '水平展示',
			'sidebar/command/voice/hidden': '隐藏模式',
			'sidebar/command/voice/visible': '显示模式',
			'sidebar/command/voice/showYuelu': '展示岳麓山校区',
			'sidebar/command/voice/showLunan': '展示麓南校区',
			'sidebar/command/voice/showXiaoxiang': '展示潇湘校区',
			'sidebar/command/voice/showTianxin': '展示天心校区',
			'sidebar/command/voice/showXinglin': '展示杏林校区',
			'sidebar/command/voice/showKaifu': '展示开福校区',
			'sidebar/command/voice/goBack': '返回',
			'sidebar/command/voice/bgmOn': '打开背景音乐',
			'sidebar/command/voice/bgmOff': '关闭背景音乐',
			'sidebar/command/voice/sandboxFxOn': '打开沙盘特效',
			'sidebar/command/voice/sandboxFxOff': '关闭沙盘特效',


			'sidebar/entity': '实体（自定义）',
			'sidebar/entity/button': '编辑',

			'sidebar/confirm/scene/modified': '场景发生了修改，是否保存?',

			'sidebar/geometry/type': '类型',
			'sidebar/geometry/new': '更新',
			'sidebar/geometry/uuid': '识别码',
			'sidebar/geometry/name': '名称',
			'sidebar/geometry/bounds': '界限',
			'sidebar/geometry/show_vertex_normals': '显示顶点法线',

			'sidebar/geometry/box_geometry/width': '宽度',
			'sidebar/geometry/box_geometry/height': '高度',
			'sidebar/geometry/box_geometry/depth': '深度',
			'sidebar/geometry/box_geometry/widthseg': '宽度分段',
			'sidebar/geometry/box_geometry/heightseg': '高度分段',
			'sidebar/geometry/box_geometry/depthseg': '深度分段',

			'sidebar/geometry/buffer_geometry/attributes': '属性',
			'sidebar/geometry/buffer_geometry/index': '索引',

			'sidebar/geometry/capsule_geometry/radius': '半径',
			'sidebar/geometry/capsule_geometry/length': '长度',
			'sidebar/geometry/capsule_geometry/capseg': '胶囊分段',
			'sidebar/geometry/capsule_geometry/radialseg': '半径分段',

			'sidebar/geometry/circle_geometry/radius': '半径',
			'sidebar/geometry/circle_geometry/segments': '分段',
			'sidebar/geometry/circle_geometry/thetastart': '弧度起点',
			'sidebar/geometry/circle_geometry/thetalength': '弧度长度',

			'sidebar/geometry/cylinder_geometry/radiustop': '顶部半径',
			'sidebar/geometry/cylinder_geometry/radiusbottom': '底部半径',
			'sidebar/geometry/cylinder_geometry/height': '高度',
			'sidebar/geometry/cylinder_geometry/radialsegments': '径向分段',
			'sidebar/geometry/cylinder_geometry/heightsegments': '高度分段',
			'sidebar/geometry/cylinder_geometry/openended': '开端',

			'sidebar/geometry/extrude_geometry/curveSegments': '曲线段',
			'sidebar/geometry/extrude_geometry/steps': '细分点数',
			'sidebar/geometry/extrude_geometry/depth': '深度',
			'sidebar/geometry/extrude_geometry/bevelEnabled': '启用斜角',
			'sidebar/geometry/extrude_geometry/bevelThickness': '斜角厚度',
			'sidebar/geometry/extrude_geometry/bevelSize': '斜角大小',
			'sidebar/geometry/extrude_geometry/bevelOffset': '斜角偏移量',
			'sidebar/geometry/extrude_geometry/bevelSegments': '斜角分段',
			'sidebar/geometry/extrude_geometry/shape': '转换图形',

			'sidebar/geometry/dodecahedron_geometry/radius': '半径',
			'sidebar/geometry/dodecahedron_geometry/detail': '面片分段',

			'sidebar/geometry/icosahedron_geometry/radius': '半径',
			'sidebar/geometry/icosahedron_geometry/detail': '面片分段',

			'sidebar/geometry/octahedron_geometry/radius': '半径',
			'sidebar/geometry/octahedron_geometry/detail': '面片分段',

			'sidebar/geometry/tetrahedron_geometry/radius': '半径',
			'sidebar/geometry/tetrahedron_geometry/detail': '面片分段',

			'sidebar/geometry/lathe_geometry/segments': '分段',
			'sidebar/geometry/lathe_geometry/phistart': '经度起点',
			'sidebar/geometry/lathe_geometry/philength': '经度长度',
			'sidebar/geometry/lathe_geometry/points': '点',

			'sidebar/geometry/plane_geometry/width': '宽度',
			'sidebar/geometry/plane_geometry/height': '长度',
			'sidebar/geometry/plane_geometry/widthsegments': '宽度分段',
			'sidebar/geometry/plane_geometry/heightsegments': '长度分段',

			'sidebar/geometry/ring_geometry/innerRadius': '内半径',
			'sidebar/geometry/ring_geometry/outerRadius': '外半径',
			'sidebar/geometry/ring_geometry/thetaSegments': '弧度分段',
			'sidebar/geometry/ring_geometry/phiSegments': '经度分段',
			'sidebar/geometry/ring_geometry/thetastart': '弧度起点',
			'sidebar/geometry/ring_geometry/thetalength': '弧度长度',

			'sidebar/geometry/shape_geometry/curveSegments': '曲线段',
			'sidebar/geometry/shape_geometry/extrude': '拉伸',

			'sidebar/geometry/sphere_geometry/radius': '半径',
			'sidebar/geometry/sphere_geometry/widthsegments': '宽度分段',
			'sidebar/geometry/sphere_geometry/heightsegments': '长度分段',
			'sidebar/geometry/sphere_geometry/phistart': '经度起点',
			'sidebar/geometry/sphere_geometry/philength': '经度长度',
			'sidebar/geometry/sphere_geometry/thetastart': '纬度起点',
			'sidebar/geometry/sphere_geometry/thetalength': '纬度长度',

			'sidebar/geometry/torus_geometry/radius': '半径',
			'sidebar/geometry/torus_geometry/tube': '管厚',
			'sidebar/geometry/torus_geometry/radialsegments': '半径分段',
			'sidebar/geometry/torus_geometry/tubularsegments': '管厚分段',
			'sidebar/geometry/torus_geometry/arc': '弧度',

			'sidebar/geometry/torusKnot_geometry/radius': '半径',
			'sidebar/geometry/torusKnot_geometry/tube': '管厚',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': '管厚分段',
			'sidebar/geometry/torusKnot_geometry/radialsegments': '半径分段',
			'sidebar/geometry/torusKnot_geometry/p': '管长弧度',
			'sidebar/geometry/torusKnot_geometry/q': '扭曲弧度',

			'sidebar/geometry/tube_geometry/path': '路径',
			'sidebar/geometry/tube_geometry/radius': '半径',
			'sidebar/geometry/tube_geometry/tube': '管厚',
			'sidebar/geometry/tube_geometry/tubularsegments': '管厚分段',
			'sidebar/geometry/tube_geometry/radialsegments': '半径分段',
			'sidebar/geometry/tube_geometry/closed': '闭合',
			'sidebar/geometry/tube_geometry/curvetype': '曲线类型',
			'sidebar/geometry/tube_geometry/tension': '张力',

			'sidebar/material/new': '更新',
			'sidebar/material/copy': '复制',
			'sidebar/material/paste': '粘贴',
			'sidebar/material/slot': '插槽',
			'sidebar/material/type': '类型',
			'sidebar/material/uuid': '识别码',
			'sidebar/material/name': '名称',
			'sidebar/material/program': '程序',
			'sidebar/material/info': '信息',
			'sidebar/material/vertex': '顶点',
			'sidebar/material/fragment': '片元',
			'sidebar/material/color': '颜色',
			'sidebar/material/depthPacking': '深度包装',
			'sidebar/material/roughness': '粗糙度',
			'sidebar/material/metalness': '金属度',
			'sidebar/material/reflectivity': '反射率',
			'sidebar/material/emissive': '自发光',
			'sidebar/material/specular': '高光',
			'sidebar/material/shininess': '高光大小',
			'sidebar/material/clearcoat': '清漆',
			'sidebar/material/clearcoatroughness': '清漆粗糙度',
			'sidebar/material/transmission': '透光',
			'sidebar/material/attenuationDistance': '衰减距离',
			'sidebar/material/attenuationColor': '衰减颜色',
			'sidebar/material/thickness': '厚度',
			'sidebar/material/vertexcolors': '顶点颜色',
			'sidebar/material/matcap': '材质捕获',
			'sidebar/material/map': '贴图',
			'sidebar/material/alphamap': '透明贴图',
			'sidebar/material/bumpmap': '凹凸贴图',
			'sidebar/material/normalmap': '法线贴图',
			'sidebar/material/clearcoatnormalmap': '清漆法线贴图',
			'sidebar/material/displacementmap': '置换贴图',
			'sidebar/material/roughnessmap': '粗糙贴图',
			'sidebar/material/metalnessmap': '金属贴图',
			'sidebar/material/specularmap': '高光贴图',
			'sidebar/material/envmap': '环境贴图',
			'sidebar/material/lightmap': '光照贴图',
			'sidebar/material/aomap': '环境光遮蔽贴图',
			'sidebar/material/emissivemap': '自发光贴图',
			'sidebar/material/gradientmap': '渐变贴图',
			'sidebar/material/side': '面',
			'sidebar/material/size': '大小',
			'sidebar/material/sizeAttenuation': '大小衰减',
			'sidebar/material/flatShading': '平面着色',
			'sidebar/material/blending': '混合',
			'sidebar/material/opacity': '透明度',
			'sidebar/material/transparent': '透明性',
			'sidebar/material/alphatest': 'α测试',
			'sidebar/material/depthtest': '深度测试',
			'sidebar/material/depthwrite': '深度缓冲',
			'sidebar/material/wireframe': '线框',
			'sidebar/material/userdata': '自定义数据',

			'sidebar/script': '脚本',
			'sidebar/script/new': '新建',
			'sidebar/script/edit': '编辑',
			'sidebar/script/remove': '删除',

			'sidebar/project': '项目',
			'sidebar/project/title': '标题',
			'sidebar/project/editable': '编辑性',
			'sidebar/project/vr': '虚拟现实',
			'sidebar/project/renderer': '渲染器',
			'sidebar/project/antialias': '抗锯齿',
			'sidebar/project/shadows': '阴影',
			'sidebar/project/physicallyCorrectLights': '物理灯',
			'sidebar/project/toneMapping': '色调映射',
			'sidebar/project/materials': '材质',
			'sidebar/project/Assign': '应用',

			'sidebar/project/video': '视频',
			'sidebar/project/resolution': '分辨率',
			'sidebar/project/duration': '时长',
			'sidebar/project/render': '渲染',

			'sidebar/settings': '设置',
			'sidebar/settings/language': '语言',

			'sidebar/settings/shortcuts': '快捷键',
			'sidebar/settings/shortcuts/translate': '移动',
			'sidebar/settings/shortcuts/rotate': '旋转',
			'sidebar/settings/shortcuts/scale': '缩放',
			'sidebar/settings/shortcuts/undo': '撤销',
			'sidebar/settings/shortcuts/focus': '聚焦',
			'sidebar/settings/shortcuts/save': '保存',

			'sidebar/settings/viewport': '视窗',
			'sidebar/settings/viewport/grid': '网格',
			'sidebar/settings/viewport/helpers': '辅助',

			'sidebar/history': '历史记录',
			'sidebar/history/persistent': '本地存储',

			'toolbar/translate': '移动',
			'toolbar/rotate': '旋转',
			'toolbar/scale': '缩放',
			'toolbar/local': '本地',

			'viewport/info/objects': '物体',
			'viewport/info/vertices': '顶点',
			'viewport/info/triangles': '三角形',
			'viewport/info/frametime': '帧时',
			'sidebar/screenshot': '截图',
			'sidebar/screenshot/resolution': '分辨率',
			'sidebar/screenshot/resolution/current': '当前视口',
			'sidebar/screenshot/background': '背景色',
			'sidebar/screenshot/background/original': '原始背景',
			'sidebar/screenshot/background/white': '白色背景',
			'sidebar/screenshot/background/light': '浅色背景',
			'sidebar/screenshot/background/dark': '深色背景',
			'sidebar/screenshot/background/black': '黑色背景',
			'sidebar/screenshot/filename': '文件名',
			'sidebar/screenshot/format': '格式',
			'sidebar/screenshot/capture': '截取快照',
			'sidebar/screenshot/preview': '预览',
			'sidebar/screenshot/download': '下载图片',
			'sidebar/screenshot/uploadAsCover': '上传作为封面',
			'sidebar/screenshot/upload': '上传作为封面',
			'sidebar/screenshot/cancel': '取消',

			'menubar/screenshot': '截图',
			'menubar/screenshot/capture': '截取快照',
			'menubar/screenshot/confirm_upload': '截图成功！是否上传为封面？',
			'menubar/screenshot/uploading': '正在上传封面...',
			'menubar/screenshot/upload_canceled': '上传已取消',
			'menubar/screenshot/error/viewport_not_found': '无法找到视口元素',
			'menubar/screenshot/error/canvas_not_found': '无法找到渲染画布',
			'menubar/screenshot/error/capture_failed': '截图失败',
			'menubar/screenshot/download': '下载图片',
			'menubar/screenshot/downloaded': '图片已下载: ',
			'menubar/screenshot/upload': '上传作为封面',
			'menubar/screenshot/cancel': '取消',

			'menubar/component/confirm': '你想将"{0}"组件添加到当前对象吗？',
			'menubar/component/success': '成功添加"{0}"组件',
			'menubar/component/select_object_first': '请先选择一个对象',

			'menubar/command/confirm': '你想将"{0}"命令添加到当前对象吗？',
			'menubar/command/success': '成功添加"{0}"命令',
			'menubar/command/select_object_first': '请先选择一个对象',
			'menubar/command/already_exists': '此对象已添加语音指令，不能重复添加',
			'menubar/component/mutually_exclusive': '只能选择一个互斥组件：点击触发、可移动或碰撞触发',

			'sidebar/media': '媒体控制',
			'sidebar/media/play': '播放',
			'sidebar/media/pause': '暂停',
			'sidebar/media/time': '时间',
			'sidebar/media/volume': '音量',
			'sidebar/media/speed': '速度',
			'sidebar/media/loop': '循环',
			'sidebar/media/muted': '静音'
		},

		ja: {
			'menubar/file': 'ファイル',
			'menubar/file/new': '新規作成',
			'menubar/file/import': 'インポート',
			'menubar/file/save': '保存',
			'menubar/file/export/geometry': 'ジオメトリをエクスポート',
			'menubar/file/export/object': 'オブジェクトをエクスポート',
			'menubar/file/export/scene': 'シーンをエクスポート',
			'menubar/file/export/dae': 'DAEをエクスポート',
			'menubar/file/export/drc': 'DRCをエクスポート',
			'menubar/file/export/glb': 'GLBをエクスポート',
			'menubar/file/export/gltf': 'GLTFをエクスポート',
			'menubar/file/export/obj': 'OBJをエクスポート',
			'menubar/file/export/ply': 'PLYをエクスポート',
			'menubar/file/export/ply_binary': 'PLY（バイナリ）をエクスポート',
			'menubar/file/export/stl': 'STLをエクスポート',
			'menubar/file/export/stl_binary': 'STL（バイナリ）をエクスポート',
			'menubar/file/export/usdz': 'USDZをエクスポート',
			'menubar/file/publish': '公開',

			'menubar/edit': '編集',
			'menubar/edit/undo': '元に戻す (Ctrl+Z)',
			'menubar/edit/redo': 'やり直し (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': '履歴をクリア',
			'menubar/edit/center': '中央揃え',
			'menubar/edit/clone': 'コピー',
			'menubar/edit/delete': '削除 (Del)',
			'menubar/edit/fixcolormaps': 'カラーマップを修正',

			'menubar/add': '追加',
			'menubar/add/node': 'ノード',
			'menubar/add/text': 'テキスト',
			'menubar/add/voxel': 'ボクセル',
			'menubar/add/phototype': 'Phototype',
			'menubar/add/polygen': 'モデル',
			'menubar/add/audio': 'オーディオ',
			'menubar/add/picture': '画像',
			'menubar/add/video': 'ビデオ',
			'menubar/add/particle': 'パーティクル',
			'menubar/add/meta': 'コンポーネント',
			'menubar/add/prefab': 'プレハブ',
			'menubar/add/group': 'グループ',
			'menubar/add/plane': '平面',
			'menubar/add/box': '立方体',
			'menubar/add/capsule': 'カプセル',
			'menubar/add/circle': '円',
			'menubar/add/cylinder': '円柱',
			'menubar/add/ring': 'リング',
			'menubar/add/sphere': '球体',
			'menubar/add/dodecahedron': '十二面体',
			'menubar/add/icosahedron': '二十面体',
			'menubar/add/octahedron': '八面体',
			'menubar/add/tetrahedron': '四面体',
			'menubar/add/torus': 'トーラス',
			'menubar/add/torusknot': 'トーラスノット',
			'menubar/add/tube': 'チューブ',
			'menubar/add/lathe': 'ラザ',
			'menubar/add/sprite': 'スプライト',
			'menubar/add/pointlight': 'ポイントライト',
			'menubar/add/spotlight': 'スポットライト',
			'menubar/add/directionallight': '平行光源',
			'menubar/add/hemispherelight': '半球光源',
			'menubar/add/ambientlight': '環境光',
			'menubar/add/perspectivecamera': '透視カメラ',
			'menubar/add/orthographiccamera': '直交カメラ',

			'menubar/replace': '置換',
			'menubar/replace/polygen': 'モデル',
			'menubar/replace/voxel': 'ボクセル',
			'menubar/replace/picture': '画像',
			'menubar/replace/noselection': '先にオブジェクトを選択してください',
			'menubar/replace/success': '成功しました',
			'menubar/component': 'コンポーネント',
			'menubar/component/list': 'コンポーネントを表示',
			'menubar/component/confirm': '現在のオブジェクトに "{0}" コンポーネントを追加しますか？',
			'menubar/component/success': '"{0}" コンポーネントが正常に追加されました',
			'menubar/component/select_object_first': '先にオブジェクトを選択してください',

			'menubar/command': 'コマンド',
			'menubar/command/list': 'コマンドを表示',
			'menubar/command/confirm': '現在のオブジェクトに "{0}" コマンドを追加しますか？',
			'menubar/command/success': '"{0}" コマンドが正常に追加されました',
			'menubar/command/select_object_first': '先にオブジェクトを選択してください',
			'menubar/command/already_exists': 'このオブジェクトは既に音声コマンドが設定されています。別の音声コマンドを追加することはできません。',

			'menubar/code': 'コーディング',
			'menubar/code/script': 'スクリプト編集',

			'menubar/status/autosave': '自動保存',

			'menubar/play': '再生',
			'menubar/play/stop': '停止',
			'menubar/play/play': '再生',

			'menubar/examples': 'サンプル',
			'menubar/examples/Arkanoid': 'ブロック崩し',
			'menubar/examples/Camera': 'カメラ',
			'menubar/examples/Particles': 'パーティクル',
			'menubar/examples/Pong': 'ポンゲーム',
			'menubar/examples/Shaders': 'シェーダー',

			'menubar/view': 'ビュー',
			'menubar/view/fullscreen': '全画面表示',

			'menubar/help': 'ヘルプ',
			'menubar/help/source_code': 'ソースコード',
			'menubar/help/icons': 'アイコンコンポーネントパック',
			'menubar/help/about': 'このソフトウェアについて',
			'menubar/help/manual': 'マニュアル',

			'sidebar/animations': 'アニメーション',
			'sidebar/animations/play': '再生',
			'sidebar/animations/stop': '停止',
			'sidebar/animations/timescale': '時間スケール',
			'sidebar/animations/select': '選択項目',

			'sidebar/scene': 'シーン',
			'sidebar/scene/background': '背景',
			'sidebar/scene/environment': '環境',
			'sidebar/scene/fog': '霧',

			'sidebar/properties/object': 'プロパティ',
			'sidebar/properties/geometry': 'ジオメトリコンポーネント',
			'sidebar/properties/material': 'マテリアルコンポーネント',
			'sidebar/properties/script': 'スクリプト',

			'sidebar/object/type': 'タイプ',
			'sidebar/object/new': '更新',
			'sidebar/object/uuid': '識別子',
			'sidebar/object/name': '名前',
			'sidebar/object/position': '位置',
			'sidebar/object/rotation': '回転',
			'sidebar/object/isRotating': '起動時に回転',
			'sidebar/object/scale': 'スケール',
			'sidebar/object/fov': '視野角',
			'sidebar/object/left': '左',
			'sidebar/object/right': '右',
			'sidebar/object/top': '上',
			'sidebar/object/bottom': '下',
			'sidebar/object/near': '近距離',
			'sidebar/object/far': '遠距離',
			'sidebar/object/intensity': '強度',
			'sidebar/object/color': '色',
			'sidebar/object/groundcolor': '地面色',
			'sidebar/object/distance': '距離',
			'sidebar/object/angle': '角度',
			'sidebar/object/penumbra': '周辺',
			'sidebar/object/decay': '減衰',
			'sidebar/object/shadow': '影',
			'sidebar/object/shadowBias': '影のバイアス',
			'sidebar/object/shadowNormalBias': '影の法線バイアス',
			'sidebar/object/shadowRadius': '影の半径',
			'sidebar/object/cast': 'キャスト',
			'sidebar/object/receive': '受信',
			'sidebar/object/visible': '可視性',
			'sidebar/object/loop': 'ループ再生',
			'sidebar/object/frustumcull': '視錐体カリング',
			'sidebar/object/renderorder': 'レンダリング順序',
			'sidebar/object/text': 'テキストコンテンツ',
			'sidebar/object/userdata': 'ユーザーデータ',

			'sidebar/components': 'コンポーネント',
			'sidebar/components/select': '選択項目',
			'sidebar/components/select/rotate': '自動回転',
			'sidebar/components/select/action': 'クリックトリガー',
			'sidebar/components/select/moved': '移動可能',
			'sidebar/components/select/trigger': '衝突トリガー',
			'sidebar/components/select/button': '新規作成',
			'sidebar/components/select/tooltip': 'ラベル',
			'sidebar/components/remove/confirm': 'このコンポーネントを削除しますか？',
			'sidebar/components/tooltip/text': 'テキスト',
			'sidebar/components/tooltip/length': '長さ',
			'sidebar/components/tooltip/target': 'ターゲット位置',
			'sidebar/command': 'コマンド',
			'sidebar/command/select': '選択項目',
			'sidebar/command/select/voice': '音声コマンド',
			'sidebar/command/select/button': '新規作成',
			'sidebar/command/remove': '削除',
			'sidebar/command/remove/confirm': 'このコマンドを削除しますか？',
			'sidebar/command/voice/id': '識別子',
			'sidebar/command/voice/label': '音声',
			'sidebar/command/voice/scaleUp': '拡大',
			'sidebar/command/voice/scaleDown': '縮小',
			'sidebar/command/voice/decompose': '分解',
			'sidebar/command/voice/reset': 'リセット',
			'sidebar/command/voice/nextStep': '次のステップ',
			'sidebar/command/voice/returnMain': 'メイン画面に戻る',
			'sidebar/command/voice/closeTooltip': '説明カードを閉じる',
			'sidebar/command/voice/openTooltip': '説明カードを開く',
			'sidebar/command/voice/vertical': '垂直展示',
			'sidebar/command/voice/horizontal': '水平展示',
			'sidebar/command/voice/hidden': '隠しモード',
			'sidebar/command/voice/visible': '表示モード',
			'sidebar/command/voice/showYuelu': '岳麓山キャンパスを表示',
			'sidebar/command/voice/showLunan': '麓南キャンパスを表示',
			'sidebar/command/voice/showXiaoxiang': '潇湘キャンパスを表示',
			'sidebar/command/voice/showTianxin': '天心キャンパスを表示',
			'sidebar/command/voice/showXinglin': '杏林キャンパスを表示',
			'sidebar/command/voice/showKaifu': '開福キャンパスを表示',
			'sidebar/command/voice/goBack': '戻る',
			'sidebar/command/voice/bgmOn': '背景音楽を再生',
			'sidebar/command/voice/bgmOff': '背景音楽を停止',
			'sidebar/command/voice/sandboxFxOn': 'サンドボックスエフェクトを有効化',
			'sidebar/command/voice/sandboxFxOff': 'サンドボックスエフェクトを無効化',

			'sidebar/entity': 'コンポーネント（カスタム）',
			'sidebar/entity/button': '編集',

			'sidebar/confirm/scene/modified': 'シーンが変更されました。保存しますか？',

			'sidebar/geometry/type': 'タイプ',
			'sidebar/geometry/new': '更新',
			'sidebar/geometry/uuid': '識別子',
			'sidebar/geometry/name': '名前',
			'sidebar/geometry/bounds': '境界',
			'sidebar/geometry/show_vertex_normals': '頂点法線の表示',

			'sidebar/geometry/box_geometry/width': '幅',
			'sidebar/geometry/box_geometry/height': '高さ',
			'sidebar/geometry/box_geometry/depth': '奥行き',
			'sidebar/geometry/box_geometry/widthseg': '幅セグメント',
			'sidebar/geometry/box_geometry/heightseg': '高さセグメント',
			'sidebar/geometry/box_geometry/depthseg': '奥行きセグメント',

			'sidebar/geometry/buffer_geometry/attributes': '属性',
			'sidebar/geometry/buffer_geometry/index': 'インデックス',

			'sidebar/geometry/capsule_geometry/radius': '半径',
			'sidebar/geometry/capsule_geometry/length': '長さ',
			'sidebar/geometry/capsule_geometry/capseg': 'カプセルセグメント',
			'sidebar/geometry/capsule_geometry/radialseg': '半径セグメント',

			'sidebar/geometry/circle_geometry/radius': '半径',
			'sidebar/geometry/circle_geometry/segments': 'セグメント数',
			'sidebar/geometry/circle_geometry/thetastart': '開始角度',
			'sidebar/geometry/circle_geometry/thetalength': '角度長さ',

			'sidebar/geometry/cylinder_geometry/radiustop': '上部半径',
			'sidebar/geometry/cylinder_geometry/radiusbottom': '下部半径',
			'sidebar/geometry/cylinder_geometry/height': '高さ',
			'sidebar/geometry/cylinder_geometry/radialsegments': '径方向セグメント',
			'sidebar/geometry/cylinder_geometry/heightsegments': '高さセグメント',
			'sidebar/geometry/cylinder_geometry/openended': '開放端',

			'sidebar/geometry/extrude_geometry/curveSegments': '曲線セグメント',
			'sidebar/geometry/extrude_geometry/steps': '細分数',
			'sidebar/geometry/extrude_geometry/depth': '深さ',
			'sidebar/geometry/extrude_geometry/bevelEnabled': 'ベベル有効化',
			'sidebar/geometry/extrude_geometry/bevelThickness': 'ベベル厚さ',
			'sidebar/geometry/extrude_geometry/bevelSize': 'ベベルサイズ',
			'sidebar/geometry/extrude_geometry/bevelOffset': 'ベベルオフセット',
			'sidebar/geometry/extrude_geometry/bevelSegments': 'ベベルセグメント',
			'sidebar/geometry/extrude_geometry/shape': '形状変換',

			'sidebar/geometry/dodecahedron_geometry/radius': '半径',
			'sidebar/geometry/dodecahedron_geometry/detail': '面片分割',

			'sidebar/geometry/icosahedron_geometry/radius': '半径',
			'sidebar/geometry/icosahedron_geometry/detail': '面片分割',

			'sidebar/geometry/octahedron_geometry/radius': '半径',
			'sidebar/geometry/octahedron_geometry/detail': '面片分割',

			'sidebar/geometry/tetrahedron_geometry/radius': '半径',
			'sidebar/geometry/tetrahedron_geometry/detail': '面片分割',

			'sidebar/geometry/lathe_geometry/segments': '分割数',
			'sidebar/geometry/lathe_geometry/phistart': '経度の開始点',
			'sidebar/geometry/lathe_geometry/philength': '経度の長さ',
			'sidebar/geometry/lathe_geometry/points': '点数',

			'sidebar/geometry/plane_geometry/width': '幅',
			'sidebar/geometry/plane_geometry/height': '長さ',
			'sidebar/geometry/plane_geometry/widthsegments': '幅の分割',
			'sidebar/geometry/plane_geometry/heightsegments': '長さの分割',

			'sidebar/geometry/ring_geometry/innerRadius': '内半径',
			'sidebar/geometry/ring_geometry/outerRadius': '外半径',
			'sidebar/geometry/ring_geometry/thetaSegments': '角度分割',
			'sidebar/geometry/ring_geometry/phiSegments': '経度分割',
			'sidebar/geometry/ring_geometry/thetastart': '角度の開始点',
			'sidebar/geometry/ring_geometry/thetalength': '角度の長さ',

			'sidebar/geometry/shape_geometry/curveSegments': '曲線分割',
			'sidebar/geometry/shape_geometry/extrude': '押し出し',

			'sidebar/geometry/sphere_geometry/radius': '半径',
			'sidebar/geometry/sphere_geometry/widthsegments': '幅の分割',
			'sidebar/geometry/sphere_geometry/heightsegments': '高さの分割',
			'sidebar/geometry/sphere_geometry/phistart': '経度の開始点',
			'sidebar/geometry/sphere_geometry/philength': '経度の長さ',
			'sidebar/geometry/sphere_geometry/thetastart': '緯度の開始点',
			'sidebar/geometry/sphere_geometry/thetalength': '緯度の長さ',

			'sidebar/geometry/torus_geometry/radius': '半径',
			'sidebar/geometry/torus_geometry/tube': '管の厚さ',
			'sidebar/geometry/torus_geometry/radialsegments': '半径分割',
			'sidebar/geometry/torus_geometry/tubularsegments': '管の分割',
			'sidebar/geometry/torus_geometry/arc': '弧度',

			'sidebar/geometry/torusKnot_geometry/radius': '半径',
			'sidebar/geometry/torusKnot_geometry/tube': '管の厚さ',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': '管の分割',
			'sidebar/geometry/torusKnot_geometry/radialsegments': '半径分割',
			'sidebar/geometry/torusKnot_geometry/p': '管の曲率',
			'sidebar/geometry/torusKnot_geometry/q': 'ねじれの角度',

			'sidebar/geometry/tube_geometry/path': 'パス',
			'sidebar/geometry/tube_geometry/radius': '半径',
			'sidebar/geometry/tube_geometry/tube': '管の厚さ',
			'sidebar/geometry/tube_geometry/tubularsegments': '管の分割',
			'sidebar/geometry/tube_geometry/radialsegments': '半径分割',
			'sidebar/geometry/tube_geometry/closed': '閉じる',
			'sidebar/geometry/tube_geometry/curvetype': '曲線タイプ',
			'sidebar/geometry/tube_geometry/tension': '張力',

			'sidebar/material/new': '更新',
			'sidebar/material/copy': 'コピー',
			'sidebar/material/paste': '貼り付け',
			'sidebar/material/slot': 'スロット',
			'sidebar/material/type': 'タイプ',
			'sidebar/material/uuid': '識別子',
			'sidebar/material/name': '名前',
			'sidebar/material/program': 'プログラム',
			'sidebar/material/info': '情報',
			'sidebar/material/vertex': '頂点',
			'sidebar/material/fragment': 'フラグメント',
			'sidebar/material/color': '色',
			'sidebar/material/depthPacking': '深度パッキング',
			'sidebar/material/roughness': '粗さ',
			'sidebar/material/metalness': '金属性',
			'sidebar/material/reflectivity': '反射率',
			'sidebar/material/emissive': '発光',
			'sidebar/material/specular': '鏡面反射',
			'sidebar/material/shininess': '光沢',
			'sidebar/material/clearcoat': 'クリアコート',
			'sidebar/material/clearcoatroughness': 'クリアコートの粗さ',
			'sidebar/material/transmission': '透過',
			'sidebar/material/attenuationDistance': '減衰距離',
			'sidebar/material/attenuationColor': '減衰色',
			'sidebar/material/thickness': '厚さ',
			'sidebar/material/vertexcolors': '頂点色',
			'sidebar/material/matcap': 'マテリアルキャプチャ',
			'sidebar/material/map': 'テクスチャ',
			'sidebar/material/alphamap': 'アルファマップ',
			'sidebar/material/bumpmap': 'バンプマップ',
			'sidebar/material/normalmap': '法線マップ',
			'sidebar/material/clearcoatnormalmap': 'クリアコート法線マップ',
			'sidebar/material/displacementmap': '変位マップ',
			'sidebar/material/roughnessmap': '粗さマップ',
			'sidebar/material/metalnessmap': '金属性マップ',
			'sidebar/material/specularmap': '鏡面反射マップ',
			'sidebar/material/envmap': '環境マップ',
			'sidebar/material/lightmap': 'ライトマップ',
			'sidebar/material/aomap': 'AOマップ',
			'sidebar/material/emissivemap': '発光マップ',
			'sidebar/material/gradientmap': 'グラデーションマップ',
			'sidebar/material/side': '面',
			'sidebar/material/size': 'サイズ',
			'sidebar/material/sizeAttenuation': 'サイズ減衰',
			'sidebar/material/flatShading': 'フラットシェーディング',
			'sidebar/material/blending': 'ブレンド',
			'sidebar/material/opacity': '透明度',
			'sidebar/material/transparent': '透明性',
			'sidebar/material/alphatest': 'アルファテスト',
			'sidebar/material/depthtest': '深度テスト',
			'sidebar/material/depthwrite': '深度バッファ',
			'sidebar/material/wireframe': 'ワイヤーフレーム',
			'sidebar/material/userdata': 'ユーザーデータ',

			'sidebar/script': 'スクリプト',
			'sidebar/script/new': '新規作成',
			'sidebar/script/edit': '編集',
			'sidebar/script/remove': '削除',

			'sidebar/project': 'プロジェクト',
			'sidebar/project/title': 'タイトル',
			'sidebar/project/editable': '編集可能',
			'sidebar/project/vr': 'バーチャルリアル',
			'sidebar/project/renderer': 'レンダラー',
			'sidebar/project/antialias': 'アンチエイリアス',
			'sidebar/project/shadows': '影',
			'sidebar/project/physicallyCorrectLights': '物理的正確な光源',
			'sidebar/project/toneMapping': 'トーンマッピング',
			'sidebar/project/materials': 'マテリアル',
			'sidebar/project/Assign': '適用',

			'sidebar/project/video': 'ビデオ',
			'sidebar/project/resolution': '解像度',
			'sidebar/project/duration': '時間',
			'sidebar/project/render': 'レンダリング',

			'sidebar/settings': '設定',
			'sidebar/settings/language': '言語',

			'sidebar/settings/shortcuts': 'ショートカット',
			'sidebar/settings/shortcuts/translate': '移動',
			'sidebar/settings/shortcuts/rotate': '回転',
			'sidebar/settings/shortcuts/scale': 'スケール',
			'sidebar/settings/shortcuts/undo': '元に戻す',
			'sidebar/settings/shortcuts/focus': 'フォーカス',
			'sidebar/settings/shortcuts/save': '保存',

			'sidebar/settings/viewport': 'ビューポート',
			'sidebar/settings/viewport/grid': 'グリッド',
			'sidebar/settings/viewport/helpers': 'ヘルパー',

			'sidebar/history': '履歴',
			'sidebar/history/persistent': 'ローカルストレージ',

			'toolbar/translate': '移動',
			'toolbar/rotate': '回転',
			'toolbar/scale': 'スケール',
			'toolbar/local': 'ローカル',

			'viewport/info/objects': 'オブジェクト',
			'viewport/info/vertices': '頂点',
			'viewport/info/triangles': '三角形',
			'viewport/info/frametime': 'フレーム時間',
			'sidebar/screenshot': 'スクリーンショット',
			'sidebar/screenshot/resolution': '解像度',
			'sidebar/screenshot/background': '背景色',
			'sidebar/screenshot/background/original': 'オリジナル',
			'sidebar/screenshot/background/white': '白',
			'sidebar/screenshot/background/light': '浅色',
			'sidebar/screenshot/background/dark': '暗色',
			'sidebar/screenshot/background/black': '黒',
			'sidebar/screenshot/filename': 'ファイル名',
			'sidebar/screenshot/format': 'フォーマット',
			'sidebar/screenshot/capture': 'スクリーンショットをキャプチャ',
			'sidebar/screenshot/preview': 'プレビュー',
			'sidebar/screenshot/download': '画像をダウンロード',
			'sidebar/screenshot/uploadAsCover': 'カバーとしてアップロード',
			'sidebar/screenshot/upload': 'カバーとしてアップロード',
			'sidebar/screenshot/cancel': 'キャンセル',

			'menubar/screenshot': 'スクリーンショット',
			'menubar/screenshot/capture': 'スクリーンショットをキャプチャ',
			'menubar/screenshot/confirm_upload': 'スクリーンショットが正常にキャプチャされました！カバーとしてアップロードしますか？',
			'menubar/screenshot/uploading': 'カバーをアップロード中...',
			'menubar/screenshot/upload_canceled': 'アップロードがキャンセルされました',
			'menubar/screenshot/error/viewport_not_found': 'ビューポート要素が見つかりません',
			'menubar/screenshot/error/canvas_not_found': 'レンダラーキャンバスが見つかりません',
			'menubar/screenshot/error/capture_failed': 'スクリーンショットに失敗しました',
			'menubar/screenshot/download': 'ダウンロード',
			'menubar/screenshot/downloaded': 'ダウンロード完了: ',
			'menubar/screenshot/upload': 'カバーとしてアップロード',
			'menubar/screenshot/cancel': 'キャンセル',

			'menubar/component/confirm': '現在のオブジェクトに "{0}" コンポーネントを追加しますか？',
			'menubar/component/success': '"{0}" コンポーネントが正常に追加されました',
			'menubar/component/select_object_first': '先にオブジェクトを選択してください',

			'menubar/command/confirm': '現在のオブジェクトに "{0}" コマンドを追加しますか？',
			'menubar/command/success': '"{0}" コマンドが正常に追加されました',
			'menubar/command/select_object_first': '先にオブジェクトを選択してください',
			'menubar/command/already_exists': 'このオブジェクトは既に音声コマンドが設定されています。別の音声コマンドを追加することはできません。',
			'menubar/component/mutually_exclusive': 'Only one of these components can be selected: Click Action, Movable or Collision Trigger',

			'sidebar/media': 'メディアコントロール',
			'sidebar/media/play': '再生',
			'sidebar/media/pause': '一時停止',
			'sidebar/media/time': '時間',
			'sidebar/media/volume': '音量',
			'sidebar/media/speed': '速度',
			'sidebar/media/loop': 'ループ',
			'sidebar/media/muted': 'ミュート'
		}
	};

	return {
		getKey: function ( key ) {

			return values[ language ][ key ] || '???';

		}
	};

}

export { Strings };
