// --- MRPP MODIFICATION START ---
import { mrppStrings } from '../../../plugin/i18n/MrppStrings.js';
// --- MRPP MODIFICATION END ---

function Strings(config) {

	const language = config.getKey('language');

	const values = {
		"en-us": {
			'menubar/file': 'File',
			'menubar/file/new': 'New',
			'menubar/file/import': 'Import',
			'menubar/file/save': 'Save',
			'menubar/file/export/geometry': 'Export Geometry',
			'menubar/file/export/object': 'Export Object',
			'menubar/file/export/scene': 'Export Scene',
			'menubar/file/export/dae': 'Export DAE',
			'menubar/file/export/drc': 'Export DRC',
			'menubar/file/export/glb': 'Export GLB',
			'menubar/file/export/gltf': 'Export GLTF',
			'menubar/file/export/obj': 'Export OBJ',
			'menubar/file/export/ply': 'Export PLY',
			'menubar/file/export/ply_binary': 'Export PLY (Binary)',
			'menubar/file/export/stl': 'Export STL',
			'menubar/file/export/stl_binary': 'Export STL (Binary)',
			'menubar/file/export/usdz': 'Export USDZ',
			'menubar/file/publish': 'Publish',

			'menubar/edit': 'Edit',
			'menubar/edit/undo': 'Undo (Ctrl+Z)',
			'menubar/edit/redo': 'Redo (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': 'Clear History',
			'menubar/edit/center': 'Center',
			'menubar/edit/clone': 'Clone',
			'menubar/edit/delete': 'Delete (Del)',
			'menubar/edit/fixcolormaps': 'Fix Color Maps',


			'menubar/add': 'Add',
			'menubar/add/group': 'Group',
			'menubar/add/plane': 'Plane',
			'menubar/add/box': 'Box',
			'menubar/add/capsule': 'Capsule',
			'menubar/add/circle': 'Circle',
			'menubar/add/cylinder': 'Cylinder',
			'menubar/add/ring': 'Ring',
			'menubar/add/sphere': 'Sphere',
			'menubar/add/dodecahedron': 'Dodecahedron',
			'menubar/add/icosahedron': 'Icosahedron',
			'menubar/add/octahedron': 'Octahedron',
			'menubar/add/tetrahedron': 'Tetrahedron',
			'menubar/add/torus': 'Torus',
			'menubar/add/tube': 'Tube',
			'menubar/add/torusknot': 'TorusKnot',
			'menubar/add/lathe': 'Lathe',
			'menubar/add/sprite': 'Sprite',
			'menubar/add/pointlight': 'PointLight',
			'menubar/add/spotlight': 'SpotLight',
			'menubar/add/directionallight': 'DirectionalLight',
			'menubar/add/hemispherelight': 'HemisphereLight',
			'menubar/add/ambientlight': 'AmbientLight',
			'menubar/add/perspectivecamera': 'PerspectiveCamera',
			'menubar/add/orthographiccamera': 'OrthographicCamera',


			'menubar/status/autosave': 'autosave',

			'menubar/play': 'Play',
			'menubar/play/stop': 'Stop',
			'menubar/play/play': 'Play',

			'menubar/examples': 'Examples',
			'menubar/examples/Arkanoid': 'Arkanoid',
			'menubar/examples/Camera': 'Camera',
			'menubar/examples/Particles': 'Particles',
			'menubar/examples/Pong': 'Pong',
			'menubar/examples/Shaders': 'Shaders',

			'menubar/view': 'View',
			'menubar/view/fullscreen': 'Fullscreen',

			'menubar/help': 'Help',
			'menubar/help/source_code': 'Source Code',
			'menubar/help/icons': 'Icon Pack',
			'menubar/help/about': 'About',
			'menubar/help/manual': 'Manual',


			'sidebar/scene': 'Scene',
			'sidebar/scene/background': 'Background',
			'sidebar/scene/environment': 'Environment',
			'sidebar/scene/fog': 'Fog',

			'sidebar/properties/object': 'Object',
			'sidebar/properties/geometry': 'Geometry',
			'sidebar/properties/material': 'Material',
			'sidebar/properties/script': 'Script',

			'sidebar/object/type': 'Type',
			'sidebar/object/type_value/scene': 'Scene',
			'sidebar/object/type_value/group': 'Group',
			'sidebar/object/type_value/object3d': 'Object',
			'sidebar/object/type_value/mesh': 'Mesh',
			'sidebar/object/type_value/line': 'Line',
			'sidebar/object/type_value/linesegments': 'Line Segments',
			'sidebar/object/type_value/points': 'Points',
			'sidebar/object/type_value/sprite': 'Sprite',
			'sidebar/object/type_value/camera': 'Camera',
			'sidebar/object/type_value/perspectivecamera': 'Perspective Camera',
			'sidebar/object/type_value/orthographiccamera': 'Orthographic Camera',
			'sidebar/object/type_value/light': 'Light',
			'sidebar/object/type_value/ambientlight': 'Ambient Light',
			'sidebar/object/type_value/directionallight': 'Directional Light',
			'sidebar/object/type_value/hemispherelight': 'Hemisphere Light',
			'sidebar/object/type_value/pointlight': 'Point Light',
			'sidebar/object/type_value/spotlight': 'Spot Light',
			'sidebar/object/new': 'New',
			'sidebar/object/uuid': 'UUID',
			'sidebar/object/name': 'Name',
			'sidebar/object/position': 'Position',
			'sidebar/object/rotation': 'Rotation',
			'sidebar/object/scale': 'Scale',
			'sidebar/object/fov': 'Fov',
			'sidebar/object/left': 'Left',
			'sidebar/object/right': 'Right',
			'sidebar/object/top': 'Top',
			'sidebar/object/bottom': 'Bottom',
			'sidebar/object/near': 'Near',
			'sidebar/object/far': 'Far',
			'sidebar/object/intensity': 'Intensity',
			'sidebar/object/color': 'Color',
			'sidebar/object/groundcolor': 'Ground Color',
			'sidebar/object/distance': 'Distance',
			'sidebar/object/angle': 'Angle',
			'sidebar/object/penumbra': 'Penumbra',
			'sidebar/object/decay': 'Decay',
			'sidebar/object/shadow': 'Shadow',
			'sidebar/object/shadowBias': 'Shadow Bias',
			'sidebar/object/shadowNormalBias': 'Shadow Normal Bias',
			'sidebar/object/shadowRadius': 'Shadow Radius',
			'sidebar/object/cast': 'cast',
			'sidebar/object/receive': 'receive',
			'sidebar/object/visible': 'Visible',
			'sidebar/object/frustumcull': 'Frustum Cull',
			'sidebar/object/renderorder': 'Render Order',
			'sidebar/object/userdata': 'User data',


			'sidebar/geometry/type': 'Type',
			'sidebar/geometry/new': 'New',
			'sidebar/geometry/uuid': 'UUID',
			'sidebar/geometry/name': 'Name',
			'sidebar/geometry/bounds': 'Bounds',
			'sidebar/geometry/show_vertex_normals': 'Show Vertex Normals',

			'sidebar/geometry/box_geometry/width': 'Width',
			'sidebar/geometry/box_geometry/height': 'Height',
			'sidebar/geometry/box_geometry/depth': 'Depth',
			'sidebar/geometry/box_geometry/widthseg': 'Width Seg',
			'sidebar/geometry/box_geometry/heightseg': 'Height Seg',
			'sidebar/geometry/box_geometry/depthseg': 'Depth Seg',

			'sidebar/geometry/buffer_geometry/attributes': 'Attributes',
			'sidebar/geometry/buffer_geometry/index': 'index',

			'sidebar/geometry/capsule_geometry/radius': 'Radius',
			'sidebar/geometry/capsule_geometry/length': 'Length',
			'sidebar/geometry/capsule_geometry/capseg': 'Cap Seg',
			'sidebar/geometry/capsule_geometry/radialseg': 'Radial Seg',

			'sidebar/geometry/circle_geometry/radius': 'Radius',
			'sidebar/geometry/circle_geometry/segments': 'Segments',
			'sidebar/geometry/circle_geometry/thetastart': 'Theta start',
			'sidebar/geometry/circle_geometry/thetalength': 'Theta length',

			'sidebar/geometry/cylinder_geometry/radiustop': 'Radius top',
			'sidebar/geometry/cylinder_geometry/radiusbottom': 'Radius bottom',
			'sidebar/geometry/cylinder_geometry/height': 'Height',
			'sidebar/geometry/cylinder_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/cylinder_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/cylinder_geometry/openended': 'Open ended',

			'sidebar/geometry/extrude_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/extrude_geometry/steps': 'Steps',
			'sidebar/geometry/extrude_geometry/depth': 'Depth',
			'sidebar/geometry/extrude_geometry/bevelEnabled': 'Bevel?',
			'sidebar/geometry/extrude_geometry/bevelThickness': 'Thickness',
			'sidebar/geometry/extrude_geometry/bevelSize': 'Size',
			'sidebar/geometry/extrude_geometry/bevelOffset': 'Offset',
			'sidebar/geometry/extrude_geometry/bevelSegments': 'Segments',
			'sidebar/geometry/extrude_geometry/shape': 'Convert to Shape',

			'sidebar/geometry/dodecahedron_geometry/radius': 'Radius',
			'sidebar/geometry/dodecahedron_geometry/detail': 'Detail',

			'sidebar/geometry/icosahedron_geometry/radius': 'Radius',
			'sidebar/geometry/icosahedron_geometry/detail': 'Detail',

			'sidebar/geometry/octahedron_geometry/radius': 'Radius',
			'sidebar/geometry/octahedron_geometry/detail': 'Detail',

			'sidebar/geometry/tetrahedron_geometry/radius': 'Radius',
			'sidebar/geometry/tetrahedron_geometry/detail': 'Detail',

			'sidebar/geometry/lathe_geometry/segments': 'Segments',
			'sidebar/geometry/lathe_geometry/phistart': 'Phi start (°)',
			'sidebar/geometry/lathe_geometry/philength': 'Phi length (°)',
			'sidebar/geometry/lathe_geometry/points': 'Points',

			'sidebar/geometry/plane_geometry/width': 'Width',
			'sidebar/geometry/plane_geometry/height': 'Height',
			'sidebar/geometry/plane_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/plane_geometry/heightsegments': 'Height segments',

			'sidebar/geometry/ring_geometry/innerRadius': 'Inner radius',
			'sidebar/geometry/ring_geometry/outerRadius': 'Outer radius',
			'sidebar/geometry/ring_geometry/thetaSegments': 'Theta segments',
			'sidebar/geometry/ring_geometry/phiSegments': 'Phi segments',
			'sidebar/geometry/ring_geometry/thetastart': 'Theta start',
			'sidebar/geometry/ring_geometry/thetalength': 'Theta length',

			'sidebar/geometry/shape_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/shape_geometry/extrude': 'Extrude',

			'sidebar/geometry/sphere_geometry/radius': 'Radius',
			'sidebar/geometry/sphere_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/sphere_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/sphere_geometry/phistart': 'Phi start',
			'sidebar/geometry/sphere_geometry/philength': 'Phi length',
			'sidebar/geometry/sphere_geometry/thetastart': 'Theta start',
			'sidebar/geometry/sphere_geometry/thetalength': 'Theta length',

			'sidebar/geometry/torus_geometry/radius': 'Radius',
			'sidebar/geometry/torus_geometry/tube': 'Tube',
			'sidebar/geometry/torus_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torus_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torus_geometry/arc': 'Arc',

			'sidebar/geometry/torusKnot_geometry/radius': 'Radius',
			'sidebar/geometry/torusKnot_geometry/tube': 'Tube',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torusKnot_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torusKnot_geometry/p': 'P',
			'sidebar/geometry/torusKnot_geometry/q': 'Q',

			'sidebar/geometry/tube_geometry/path': 'Path',
			'sidebar/geometry/tube_geometry/radius': 'Radius',
			'sidebar/geometry/tube_geometry/tube': 'Tube',
			'sidebar/geometry/tube_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/tube_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/tube_geometry/closed': 'Closed',
			'sidebar/geometry/tube_geometry/curvetype': 'Curve Type',
			'sidebar/geometry/tube_geometry/tension': 'Tension',

			'sidebar/material/new': 'New',
			'sidebar/material/copy': 'Copy',
			'sidebar/material/paste': 'Paste',
			'sidebar/material/slot': 'Slot',
			'sidebar/material/type': 'Type',
			'sidebar/material/uuid': 'UUID',
			'sidebar/material/name': 'Name',
			'sidebar/material/program': 'Program',
			'sidebar/material/info': 'Info',
			'sidebar/material/vertex': 'Vert',
			'sidebar/material/fragment': 'Frag',
			'sidebar/material/color': 'Color',
			'sidebar/material/depthPacking': 'Depth Packing',
			'sidebar/material/roughness': 'Roughness',
			'sidebar/material/metalness': 'Metalness',
			'sidebar/material/reflectivity': 'Reflectivity',
			'sidebar/material/emissive': 'Emissive',
			'sidebar/material/specular': 'Specular',
			'sidebar/material/shininess': 'Shininess',
			'sidebar/material/clearcoat': 'Clearcoat',
			'sidebar/material/clearcoatroughness': 'Clearcoat Roughness',
			'sidebar/material/transmission': 'Transmission',
			'sidebar/material/attenuationDistance': 'Attenuation Distance',
			'sidebar/material/attenuationColor': 'Attenuation Color',
			'sidebar/material/thickness': 'Thickness',
			'sidebar/material/vertexcolors': 'Vertex Colors',
			'sidebar/material/matcap': 'Matcap',
			'sidebar/material/map': 'Map',
			'sidebar/material/alphamap': 'Alpha Map',
			'sidebar/material/bumpmap': 'Bump Map',
			'sidebar/material/normalmap': 'Normal Map',
			'sidebar/material/clearcoatnormalmap': 'Clearcoat Normal Map',
			'sidebar/material/displacementmap': 'Displace Map',
			'sidebar/material/roughnessmap': 'Rough. Map',
			'sidebar/material/metalnessmap': 'Metal. Map',
			'sidebar/material/specularmap': 'Specular Map',
			'sidebar/material/envmap': 'Env Map',
			'sidebar/material/lightmap': 'Light Map',
			'sidebar/material/aomap': 'AO Map',
			'sidebar/material/emissivemap': 'Emissive Map',
			'sidebar/material/gradientmap': 'Gradient Map',
			'sidebar/material/side': 'Side',
			'sidebar/material/size': 'Size',
			'sidebar/material/sizeAttenuation': 'Size Attenuation',
			'sidebar/material/flatShading': 'Flat Shading',
			'sidebar/material/blending': 'Blending',
			'sidebar/material/opacity': 'Opacity',
			'sidebar/material/transparent': 'Transparent',
			'sidebar/material/alphatest': 'Alpha Test',
			'sidebar/material/depthtest': 'Depth Test',
			'sidebar/material/depthwrite': 'Depth Write',
			'sidebar/material/wireframe': 'Wireframe',
			'sidebar/material/userdata': 'User data',

			'sidebar/script': 'Script',
			'sidebar/script/new': 'New',
			'sidebar/script/edit': 'Edit',
			'sidebar/script/remove': 'Remove',

			'sidebar/project': 'Project',
			'sidebar/project/title': 'Title',
			'sidebar/project/editable': 'Editable',
			'sidebar/project/vr': 'VR',
			'sidebar/project/renderer': 'Renderer',
			'sidebar/project/antialias': 'Antialias',
			'sidebar/project/shadows': 'Shadows',
			'sidebar/project/physicallyCorrectLights': 'Physical lights',
			'sidebar/project/toneMapping': 'Tone mapping',
			'sidebar/project/materials': 'Materials',
			'sidebar/project/Assign': 'Assign',

			'sidebar/project/video': 'Video',
			'sidebar/project/resolution': 'Resolution',
			'sidebar/project/duration': 'Duration',
			'sidebar/project/render': 'Render',

			'sidebar/settings': 'Settings',
			'sidebar/settings/language': 'Language',

			'sidebar/settings/shortcuts': 'Shortcuts',
			'sidebar/settings/shortcuts/translate': 'Translate',
			'sidebar/settings/shortcuts/rotate': 'Rotate',
			'sidebar/settings/shortcuts/scale': 'Scale',
			'sidebar/settings/shortcuts/undo': 'Undo',
			'sidebar/settings/shortcuts/focus': 'Focus',
			'sidebar/settings/shortcuts/save': 'Save',

			'sidebar/settings/viewport': 'Viewport',
			'sidebar/settings/viewport/grid': 'Grid',
			'sidebar/settings/viewport/ground': 'Ground',
			'sidebar/settings/viewport/helpers': 'Helpers',

			'sidebar/history': 'History',
			'sidebar/history/persistent': 'persistent',

			'toolbar/translate': 'Translate',
			'toolbar/rotate': 'Rotate',
			'toolbar/scale': 'Scale',
			'toolbar/local': 'Local',

			'viewport/info/objects': 'Objects',
			'viewport/info/vertices': 'Vertices',
			'viewport/info/triangles': 'Triangles',
			'viewport/info/frametime': 'Frametime',

			// --- MRPP MODIFICATION START ---
			...mrppStrings["en-us"],
			// --- MRPP MODIFICATION END ---
		},

		"zh-cn": {
			'menubar/file': '文件',
			'menubar/file/new': '新建',
			'menubar/file/import': '导入',
			'menubar/file/save': '保存',
			'menubar/file/export/geometry': '导出几何体',
			'menubar/file/export/object': '导出物体',
			'menubar/file/export/scene': '导出场景',
			'menubar/file/export/dae': '导出DAE',
			'menubar/file/export/drc': '导出DRC',
			'menubar/file/export/glb': '导出GLB',
			'menubar/file/export/gltf': '导出GLTF',
			'menubar/file/export/obj': '导出OBJ',
			'menubar/file/export/ply': '导出PLY',
			'menubar/file/export/ply_binary': '导出PLY(二进制)',
			'menubar/file/export/stl': '导出STL',
			'menubar/file/export/stl_binary': '导出STL(二进制)',
			'menubar/file/export/usdz': '导出USDZ',
			'menubar/file/publish': '发布',

			'menubar/edit': '编辑',
			'menubar/edit/undo': '撤销 (Ctrl+Z)',
			'menubar/edit/redo': '重做 (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': '清空历史记录',
			'menubar/edit/center': '居中',
			'menubar/edit/clone': '拷贝',
			'menubar/edit/delete': '删除 (Del)',
			'menubar/edit/fixcolormaps': '修复颜色贴图',

			'menubar/add': '添加',
			'menubar/add/group': '组',
			'menubar/add/plane': '平面',
			'menubar/add/box': '正方体',
			'menubar/add/capsule': '胶囊',
			'menubar/add/circle': '圆',
			'menubar/add/cylinder': '圆柱体',
			'menubar/add/ring': '环',
			'menubar/add/sphere': '球体',
			'menubar/add/dodecahedron': '十二面体',
			'menubar/add/icosahedron': '二十面体',
			'menubar/add/octahedron': '八面体',
			'menubar/add/tetrahedron': '四面体',
			'menubar/add/torus': '圆环体',
			'menubar/add/torusknot': '环面纽结体',
			'menubar/add/tube': '管',
			'menubar/add/lathe': '酒杯',
			'menubar/add/sprite': '精灵',
			'menubar/add/pointlight': '点光源',
			'menubar/add/spotlight': '聚光灯',
			'menubar/add/directionallight': '平行光',
			'menubar/add/hemispherelight': '半球光',
			'menubar/add/ambientlight': '环境光',
			'menubar/add/perspectivecamera': '透视相机',
			'menubar/add/orthographiccamera': '正交相机',


			'menubar/status/autosave': '自动保存',

			'menubar/play': '启动',
			'menubar/play/stop': '暂停',
			'menubar/play/play': '启动',

			'menubar/examples': '示例',
			'menubar/examples/Arkanoid': '打砖块',
			'menubar/examples/Camera': ' 摄像机',
			'menubar/examples/Particles': '粒子',
			'menubar/examples/Pong': '乒乓球',
			'menubar/examples/Shaders': '着色器',

			'menubar/view': '视图',
			'menubar/view/fullscreen': '全屏',

			'menubar/help': '帮助',
			'menubar/help/source_code': '源码',
			'menubar/help/icons': '图标组件包',
			'menubar/help/about': '关于',
			'menubar/help/manual': '手册',


			'sidebar/scene': '场景',
			'sidebar/scene/background': '背景',
			'sidebar/scene/environment': '环境',
			'sidebar/scene/fog': '雾',

			'sidebar/properties/object': '属性',
			'sidebar/properties/geometry': '几何组件',
			'sidebar/properties/material': '材质组件',
			'sidebar/properties/script': '脚本',

			'sidebar/object/type': '类型',
			'sidebar/object/type_value/scene': '场景',
			'sidebar/object/type_value/group': '组',
			'sidebar/object/type_value/object3d': '对象',
			'sidebar/object/type_value/mesh': '网格',
			'sidebar/object/type_value/line': '线',
			'sidebar/object/type_value/linesegments': '线段',
			'sidebar/object/type_value/points': '点集',
			'sidebar/object/type_value/sprite': '精灵',
			'sidebar/object/type_value/camera': '相机',
			'sidebar/object/type_value/perspectivecamera': '透视相机',
			'sidebar/object/type_value/orthographiccamera': '正交相机',
			'sidebar/object/type_value/light': '灯光',
			'sidebar/object/type_value/ambientlight': '环境光',
			'sidebar/object/type_value/directionallight': '平行光',
			'sidebar/object/type_value/hemispherelight': '半球光',
			'sidebar/object/type_value/pointlight': '点光源',
			'sidebar/object/type_value/spotlight': '聚光灯',
			'sidebar/object/new': '更新',
			'sidebar/object/uuid': '识别码',
			'sidebar/object/name': '名称',
			'sidebar/object/position': '位置',
			'sidebar/object/rotation': '旋转',
			'sidebar/object/scale': '缩放',
			'sidebar/object/fov': '视角',
			'sidebar/object/left': '左',
			'sidebar/object/right': '右',
			'sidebar/object/top': '上',
			'sidebar/object/bottom': '下',
			'sidebar/object/near': '近点',
			'sidebar/object/far': '远点',
			'sidebar/object/intensity': '强度',
			'sidebar/object/color': '颜色',
			'sidebar/object/groundcolor': '基色',
			'sidebar/object/distance': '距离',
			'sidebar/object/angle': '角度',
			'sidebar/object/penumbra': '边缘',
			'sidebar/object/decay': '衰减',
			'sidebar/object/shadow': '阴影',
			'sidebar/object/shadowBias': '阴影偏移',
			'sidebar/object/shadowNormalBias': '阴影法线偏移',
			'sidebar/object/shadowRadius': '阴影半径',
			'sidebar/object/cast': '产生',
			'sidebar/object/receive': '接受',
			'sidebar/object/visible': '可见性',
			'sidebar/object/frustumcull': '视锥体裁剪',
			'sidebar/object/renderorder': '渲染次序',
			'sidebar/object/userdata': '自定义数据',


			'sidebar/geometry/type': '类型',
			'sidebar/geometry/new': '更新',
			'sidebar/geometry/uuid': '识别码',
			'sidebar/geometry/name': '名称',
			'sidebar/geometry/bounds': '界限',
			'sidebar/geometry/show_vertex_normals': '显示顶点法线',

			'sidebar/geometry/box_geometry/width': '宽度',
			'sidebar/geometry/box_geometry/height': '高度',
			'sidebar/geometry/box_geometry/depth': '深度',
			'sidebar/geometry/box_geometry/widthseg': '宽度分段',
			'sidebar/geometry/box_geometry/heightseg': '高度分段',
			'sidebar/geometry/box_geometry/depthseg': '深度分段',

			'sidebar/geometry/buffer_geometry/attributes': '属性',
			'sidebar/geometry/buffer_geometry/index': '索引',

			'sidebar/geometry/capsule_geometry/radius': '半径',
			'sidebar/geometry/capsule_geometry/length': '长度',
			'sidebar/geometry/capsule_geometry/capseg': '胶囊分段',
			'sidebar/geometry/capsule_geometry/radialseg': '半径分段',

			'sidebar/geometry/circle_geometry/radius': '半径',
			'sidebar/geometry/circle_geometry/segments': '分段',
			'sidebar/geometry/circle_geometry/thetastart': '弧度起点',
			'sidebar/geometry/circle_geometry/thetalength': '弧度长度',

			'sidebar/geometry/cylinder_geometry/radiustop': '顶部半径',
			'sidebar/geometry/cylinder_geometry/radiusbottom': '底部半径',
			'sidebar/geometry/cylinder_geometry/height': '高度',
			'sidebar/geometry/cylinder_geometry/radialsegments': '径向分段',
			'sidebar/geometry/cylinder_geometry/heightsegments': '高度分段',
			'sidebar/geometry/cylinder_geometry/openended': '开端',

			'sidebar/geometry/extrude_geometry/curveSegments': '曲线段',
			'sidebar/geometry/extrude_geometry/steps': '细分点数',
			'sidebar/geometry/extrude_geometry/depth': '深度',
			'sidebar/geometry/extrude_geometry/bevelEnabled': '启用斜角',
			'sidebar/geometry/extrude_geometry/bevelThickness': '斜角厚度',
			'sidebar/geometry/extrude_geometry/bevelSize': '斜角大小',
			'sidebar/geometry/extrude_geometry/bevelOffset': '斜角偏移量',
			'sidebar/geometry/extrude_geometry/bevelSegments': '斜角分段',
			'sidebar/geometry/extrude_geometry/shape': '转换图形',

			'sidebar/geometry/dodecahedron_geometry/radius': '半径',
			'sidebar/geometry/dodecahedron_geometry/detail': '面片分段',

			'sidebar/geometry/icosahedron_geometry/radius': '半径',
			'sidebar/geometry/icosahedron_geometry/detail': '面片分段',

			'sidebar/geometry/octahedron_geometry/radius': '半径',
			'sidebar/geometry/octahedron_geometry/detail': '面片分段',

			'sidebar/geometry/tetrahedron_geometry/radius': '半径',
			'sidebar/geometry/tetrahedron_geometry/detail': '面片分段',

			'sidebar/geometry/lathe_geometry/segments': '分段',
			'sidebar/geometry/lathe_geometry/phistart': '经度起点',
			'sidebar/geometry/lathe_geometry/philength': '经度长度',
			'sidebar/geometry/lathe_geometry/points': '点',

			'sidebar/geometry/plane_geometry/width': '宽度',
			'sidebar/geometry/plane_geometry/height': '长度',
			'sidebar/geometry/plane_geometry/widthsegments': '宽度分段',
			'sidebar/geometry/plane_geometry/heightsegments': '长度分段',

			'sidebar/geometry/ring_geometry/innerRadius': '内半径',
			'sidebar/geometry/ring_geometry/outerRadius': '外半径',
			'sidebar/geometry/ring_geometry/thetaSegments': '弧度分段',
			'sidebar/geometry/ring_geometry/phiSegments': '经度分段',
			'sidebar/geometry/ring_geometry/thetastart': '弧度起点',
			'sidebar/geometry/ring_geometry/thetalength': '弧度长度',

			'sidebar/geometry/shape_geometry/curveSegments': '曲线段',
			'sidebar/geometry/shape_geometry/extrude': '拉伸',

			'sidebar/geometry/sphere_geometry/radius': '半径',
			'sidebar/geometry/sphere_geometry/widthsegments': '宽度分段',
			'sidebar/geometry/sphere_geometry/heightsegments': '长度分段',
			'sidebar/geometry/sphere_geometry/phistart': '经度起点',
			'sidebar/geometry/sphere_geometry/philength': '经度长度',
			'sidebar/geometry/sphere_geometry/thetastart': '纬度起点',
			'sidebar/geometry/sphere_geometry/thetalength': '纬度长度',

			'sidebar/geometry/torus_geometry/radius': '半径',
			'sidebar/geometry/torus_geometry/tube': '管厚',
			'sidebar/geometry/torus_geometry/radialsegments': '半径分段',
			'sidebar/geometry/torus_geometry/tubularsegments': '管厚分段',
			'sidebar/geometry/torus_geometry/arc': '弧度',

			'sidebar/geometry/torusKnot_geometry/radius': '半径',
			'sidebar/geometry/torusKnot_geometry/tube': '管厚',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': '管厚分段',
			'sidebar/geometry/torusKnot_geometry/radialsegments': '半径分段',
			'sidebar/geometry/torusKnot_geometry/p': '管长弧度',
			'sidebar/geometry/torusKnot_geometry/q': '扭曲弧度',

			'sidebar/geometry/tube_geometry/path': '路径',
			'sidebar/geometry/tube_geometry/radius': '半径',
			'sidebar/geometry/tube_geometry/tube': '管厚',
			'sidebar/geometry/tube_geometry/tubularsegments': '管厚分段',
			'sidebar/geometry/tube_geometry/radialsegments': '半径分段',
			'sidebar/geometry/tube_geometry/closed': '闭合',
			'sidebar/geometry/tube_geometry/curvetype': '曲线类型',
			'sidebar/geometry/tube_geometry/tension': '张力',

			'sidebar/material/new': '更新',
			'sidebar/material/copy': '复制',
			'sidebar/material/paste': '粘贴',
			'sidebar/material/slot': '插槽',
			'sidebar/material/type': '类型',
			'sidebar/material/uuid': '识别码',
			'sidebar/material/name': '名称',
			'sidebar/material/program': '程序',
			'sidebar/material/info': '信息',
			'sidebar/material/vertex': '顶点',
			'sidebar/material/fragment': '片元',
			'sidebar/material/color': '颜色',
			'sidebar/material/depthPacking': '深度包装',
			'sidebar/material/roughness': '粗糙度',
			'sidebar/material/metalness': '金属度',
			'sidebar/material/reflectivity': '反射率',
			'sidebar/material/emissive': '自发光',
			'sidebar/material/specular': '高光',
			'sidebar/material/shininess': '高光大小',
			'sidebar/material/clearcoat': '清漆',
			'sidebar/material/clearcoatroughness': '清漆粗糙度',
			'sidebar/material/transmission': '透光',
			'sidebar/material/attenuationDistance': '衰减距离',
			'sidebar/material/attenuationColor': '衰减颜色',
			'sidebar/material/thickness': '厚度',
			'sidebar/material/vertexcolors': '顶点颜色',
			'sidebar/material/matcap': '材质捕获',
			'sidebar/material/map': '贴图',
			'sidebar/material/alphamap': '透明贴图',
			'sidebar/material/bumpmap': '凹凸贴图',
			'sidebar/material/normalmap': '法线贴图',
			'sidebar/material/clearcoatnormalmap': '清漆法线贴图',
			'sidebar/material/displacementmap': '置换贴图',
			'sidebar/material/roughnessmap': '粗糙贴图',
			'sidebar/material/metalnessmap': '金属贴图',
			'sidebar/material/specularmap': '高光贴图',
			'sidebar/material/envmap': '环境贴图',
			'sidebar/material/lightmap': '光照贴图',
			'sidebar/material/aomap': '环境光遮蔽贴图',
			'sidebar/material/emissivemap': '自发光贴图',
			'sidebar/material/gradientmap': '渐变贴图',
			'sidebar/material/side': '面',
			'sidebar/material/size': '大小',
			'sidebar/material/sizeAttenuation': '大小衰减',
			'sidebar/material/flatShading': '平面着色',
			'sidebar/material/blending': '混合',
			'sidebar/material/opacity': '透明度',
			'sidebar/material/transparent': '透明性',
			'sidebar/material/alphatest': 'α测试',
			'sidebar/material/depthtest': '深度测试',
			'sidebar/material/depthwrite': '深度缓冲',
			'sidebar/material/wireframe': '线框',
			'sidebar/material/userdata': '自定义数据',

			'sidebar/script': '脚本',
			'sidebar/script/new': '新建',
			'sidebar/script/edit': '编辑',
			'sidebar/script/remove': '删除',

			'sidebar/project': '项目',
			'sidebar/project/title': '标题',
			'sidebar/project/editable': '编辑性',
			'sidebar/project/vr': '虚拟现实',
			'sidebar/project/renderer': '渲染器',
			'sidebar/project/antialias': '抗锯齿',
			'sidebar/project/shadows': '阴影',
			'sidebar/project/physicallyCorrectLights': '物理灯',
			'sidebar/project/toneMapping': '色调映射',
			'sidebar/project/materials': '材质',
			'sidebar/project/Assign': '应用',

			'sidebar/project/video': '视频',
			'sidebar/project/resolution': '分辨率',
			'sidebar/project/duration': '时长',
			'sidebar/project/render': '渲染',

			'sidebar/settings': '设置',
			'sidebar/settings/language': '语言',

			'sidebar/settings/shortcuts': '快捷键',
			'sidebar/settings/shortcuts/translate': '移动',
			'sidebar/settings/shortcuts/rotate': '旋转',
			'sidebar/settings/shortcuts/scale': '缩放',
			'sidebar/settings/shortcuts/undo': '撤销',
			'sidebar/settings/shortcuts/focus': '聚焦',
			'sidebar/settings/shortcuts/save': '保存',

			'sidebar/settings/viewport': '视窗',
			'sidebar/settings/viewport/grid': '网格',
			'sidebar/settings/viewport/ground': '地面',
			'sidebar/settings/viewport/helpers': '辅助',

			'sidebar/history': '历史记录',
			'sidebar/history/persistent': '本地存储',

			'toolbar/translate': '移动',
			'toolbar/rotate': '旋转',
			'toolbar/scale': '缩放',
			'toolbar/local': '本地',

			'viewport/info/objects': '物体',
			'viewport/info/vertices': '顶点',
			'viewport/info/triangles': '三角形',
			'viewport/info/frametime': '帧时',

			// --- MRPP MODIFICATION START ---
			...mrppStrings["zh-cn"],
			// --- MRPP MODIFICATION END ---
		},

		"ja-jp": {
			'menubar/file': 'ファイル',
			'menubar/file/new': '新規作成',
			'menubar/file/import': 'インポート',
			'menubar/file/save': '保存',
			'menubar/file/export/geometry': 'ジオメトリをエクスポート',
			'menubar/file/export/object': 'オブジェクトをエクスポート',
			'menubar/file/export/scene': 'シーンをエクスポート',
			'menubar/file/export/dae': 'DAEをエクスポート',
			'menubar/file/export/drc': 'DRCをエクスポート',
			'menubar/file/export/glb': 'GLBをエクスポート',
			'menubar/file/export/gltf': 'GLTFをエクスポート',
			'menubar/file/export/obj': 'OBJをエクスポート',
			'menubar/file/export/ply': 'PLYをエクスポート',
			'menubar/file/export/ply_binary': 'PLY（バイナリ）をエクスポート',
			'menubar/file/export/stl': 'STLをエクスポート',
			'menubar/file/export/stl_binary': 'STL（バイナリ）をエクスポート',
			'menubar/file/export/usdz': 'USDZをエクスポート',
			'menubar/file/publish': '公開',

			'menubar/edit': '編集',
			'menubar/edit/undo': '元に戻す (Ctrl+Z)',
			'menubar/edit/redo': 'やり直し (Ctrl+Shift+Z)',
			'menubar/edit/clear_history': '履歴をクリア',
			'menubar/edit/center': '中央揃え',
			'menubar/edit/clone': 'コピー',
			'menubar/edit/delete': '削除 (Del)',
			'menubar/edit/fixcolormaps': 'カラーマップを修正',

			'menubar/add': '追加',
			'menubar/add/group': 'グループ',
			'menubar/add/plane': '平面',
			'menubar/add/box': '立方体',
			'menubar/add/capsule': 'カプセル',
			'menubar/add/circle': '円',
			'menubar/add/cylinder': '円柱',
			'menubar/add/ring': 'リング',
			'menubar/add/sphere': '球体',
			'menubar/add/dodecahedron': '十二面体',
			'menubar/add/icosahedron': '二十面体',
			'menubar/add/octahedron': '八面体',
			'menubar/add/tetrahedron': '四面体',
			'menubar/add/torus': 'トーラス',
			'menubar/add/torusknot': 'トーラスノット',
			'menubar/add/tube': 'チューブ',
			'menubar/add/lathe': 'ラザ',
			'menubar/add/sprite': 'スプライト',
			'menubar/add/pointlight': 'ポイントライト',
			'menubar/add/spotlight': 'スポットライト',
			'menubar/add/directionallight': '平行光源',
			'menubar/add/hemispherelight': '半球光源',
			'menubar/add/ambientlight': '環境光',
			'menubar/add/perspectivecamera': '透視カメラ',
			'menubar/add/orthographiccamera': '直交カメラ',


			'menubar/status/autosave': '自動保存',

			'menubar/play': '再生',
			'menubar/play/stop': '停止',
			'menubar/play/play': '再生',

			'menubar/examples': 'サンプル',
			'menubar/examples/Arkanoid': 'ブロック崩し',
			'menubar/examples/Camera': 'カメラ',
			'menubar/examples/Particles': 'パーティクル',
			'menubar/examples/Pong': 'ポンゲーム',
			'menubar/examples/Shaders': 'シェーダー',

			'menubar/view': 'ビュー',
			'menubar/view/fullscreen': '全画面表示',

			'menubar/help': 'ヘルプ',
			'menubar/help/source_code': 'ソースコード',
			'menubar/help/icons': 'アイコンコンポーネントパック',
			'menubar/help/about': 'このソフトウェアについて',
			'menubar/help/manual': 'マニュアル',


			'sidebar/scene': 'シーン',
			'sidebar/scene/background': '背景',
			'sidebar/scene/environment': '環境',
			'sidebar/scene/fog': '霧',

			'sidebar/properties/object': 'プロパティ',
			'sidebar/properties/geometry': 'ジオメトリコンポーネント',
			'sidebar/properties/material': 'マテリアルコンポーネント',
			'sidebar/properties/script': 'スクリプト',

			'sidebar/object/type': 'タイプ',
			'sidebar/object/type_value/scene': 'シーン',
			'sidebar/object/type_value/group': 'グループ',
			'sidebar/object/type_value/object3d': 'オブジェクト',
			'sidebar/object/type_value/mesh': 'メッシュ',
			'sidebar/object/type_value/line': 'ライン',
			'sidebar/object/type_value/linesegments': 'ラインセグメント',
			'sidebar/object/type_value/points': 'ポイント群',
			'sidebar/object/type_value/sprite': 'スプライト',
			'sidebar/object/type_value/camera': 'カメラ',
			'sidebar/object/type_value/perspectivecamera': '透視カメラ',
			'sidebar/object/type_value/orthographiccamera': '正投影カメラ',
			'sidebar/object/type_value/light': 'ライト',
			'sidebar/object/type_value/ambientlight': '環境光',
			'sidebar/object/type_value/directionallight': '平行光',
			'sidebar/object/type_value/hemispherelight': '半球ライト',
			'sidebar/object/type_value/pointlight': 'ポイントライト',
			'sidebar/object/type_value/spotlight': 'スポットライト',
			'sidebar/object/new': '更新',
			'sidebar/object/uuid': '識別子',
			'sidebar/object/name': '名前',
			'sidebar/object/position': '位置',
			'sidebar/object/rotation': '回転',
			'sidebar/object/scale': 'スケール',
			'sidebar/object/fov': '視野角',
			'sidebar/object/left': '左',
			'sidebar/object/right': '右',
			'sidebar/object/top': '上',
			'sidebar/object/bottom': '下',
			'sidebar/object/near': '近距離',
			'sidebar/object/far': '遠距離',
			'sidebar/object/intensity': '強度',
			'sidebar/object/color': '色',
			'sidebar/object/groundcolor': '地面色',
			'sidebar/object/distance': '距離',
			'sidebar/object/angle': '角度',
			'sidebar/object/penumbra': '周辺',
			'sidebar/object/decay': '減衰',
			'sidebar/object/shadow': '影',
			'sidebar/object/shadowBias': '影のバイアス',
			'sidebar/object/shadowNormalBias': '影の法線バイアス',
			'sidebar/object/shadowRadius': '影の半径',
			'sidebar/object/cast': 'キャスト',
			'sidebar/object/receive': '受信',
			'sidebar/object/visible': '可視性',
			'sidebar/object/frustumcull': '視錐体カリング',
			'sidebar/object/renderorder': 'レンダリング順序',
			'sidebar/object/userdata': 'ユーザーデータ',


			'sidebar/geometry/type': 'タイプ',
			'sidebar/geometry/new': '更新',
			'sidebar/geometry/uuid': '識別子',
			'sidebar/geometry/name': '名前',
			'sidebar/geometry/bounds': '境界',
			'sidebar/geometry/show_vertex_normals': '頂点法線の表示',

			'sidebar/geometry/box_geometry/width': '幅',
			'sidebar/geometry/box_geometry/height': '高さ',
			'sidebar/geometry/box_geometry/depth': '奥行き',
			'sidebar/geometry/box_geometry/widthseg': '幅セグメント',
			'sidebar/geometry/box_geometry/heightseg': '高さセグメント',
			'sidebar/geometry/box_geometry/depthseg': '奥行きセグメント',

			'sidebar/geometry/buffer_geometry/attributes': '属性',
			'sidebar/geometry/buffer_geometry/index': 'インデックス',

			'sidebar/geometry/capsule_geometry/radius': '半径',
			'sidebar/geometry/capsule_geometry/length': '長さ',
			'sidebar/geometry/capsule_geometry/capseg': 'カプセルセグメント',
			'sidebar/geometry/capsule_geometry/radialseg': '半径セグメント',

			'sidebar/geometry/circle_geometry/radius': '半径',
			'sidebar/geometry/circle_geometry/segments': 'セグメント数',
			'sidebar/geometry/circle_geometry/thetastart': '開始角度',
			'sidebar/geometry/circle_geometry/thetalength': '角度長さ',

			'sidebar/geometry/cylinder_geometry/radiustop': '上部半径',
			'sidebar/geometry/cylinder_geometry/radiusbottom': '下部半径',
			'sidebar/geometry/cylinder_geometry/height': '高さ',
			'sidebar/geometry/cylinder_geometry/radialsegments': '径方向セグメント',
			'sidebar/geometry/cylinder_geometry/heightsegments': '高さセグメント',
			'sidebar/geometry/cylinder_geometry/openended': '開放端',

			'sidebar/geometry/extrude_geometry/curveSegments': '曲線セグメント',
			'sidebar/geometry/extrude_geometry/steps': '細分数',
			'sidebar/geometry/extrude_geometry/depth': '深さ',
			'sidebar/geometry/extrude_geometry/bevelEnabled': 'ベベル有効化',
			'sidebar/geometry/extrude_geometry/bevelThickness': 'ベベル厚さ',
			'sidebar/geometry/extrude_geometry/bevelSize': 'ベベルサイズ',
			'sidebar/geometry/extrude_geometry/bevelOffset': 'ベベルオフセット',
			'sidebar/geometry/extrude_geometry/bevelSegments': 'ベベルセグメント',
			'sidebar/geometry/extrude_geometry/shape': '形状変換',

			'sidebar/geometry/dodecahedron_geometry/radius': '半径',
			'sidebar/geometry/dodecahedron_geometry/detail': '面片分割',

			'sidebar/geometry/icosahedron_geometry/radius': '半径',
			'sidebar/geometry/icosahedron_geometry/detail': '面片分割',

			'sidebar/geometry/octahedron_geometry/radius': '半径',
			'sidebar/geometry/octahedron_geometry/detail': '面片分割',

			'sidebar/geometry/tetrahedron_geometry/radius': '半径',
			'sidebar/geometry/tetrahedron_geometry/detail': '面片分割',

			'sidebar/geometry/lathe_geometry/segments': '分割数',
			'sidebar/geometry/lathe_geometry/phistart': '経度の開始点',
			'sidebar/geometry/lathe_geometry/philength': '経度の長さ',
			'sidebar/geometry/lathe_geometry/points': '点数',

			'sidebar/geometry/plane_geometry/width': '幅',
			'sidebar/geometry/plane_geometry/height': '長さ',
			'sidebar/geometry/plane_geometry/widthsegments': '幅の分割',
			'sidebar/geometry/plane_geometry/heightsegments': '長さの分割',

			'sidebar/geometry/ring_geometry/innerRadius': '内半径',
			'sidebar/geometry/ring_geometry/outerRadius': '外半径',
			'sidebar/geometry/ring_geometry/thetaSegments': '角度分割',
			'sidebar/geometry/ring_geometry/phiSegments': '経度分割',
			'sidebar/geometry/ring_geometry/thetastart': '角度の開始点',
			'sidebar/geometry/ring_geometry/thetalength': '角度の長さ',

			'sidebar/geometry/shape_geometry/curveSegments': '曲線分割',
			'sidebar/geometry/shape_geometry/extrude': '押し出し',

			'sidebar/geometry/sphere_geometry/radius': '半径',
			'sidebar/geometry/sphere_geometry/widthsegments': '幅の分割',
			'sidebar/geometry/sphere_geometry/heightsegments': '高さの分割',
			'sidebar/geometry/sphere_geometry/phistart': '経度の開始点',
			'sidebar/geometry/sphere_geometry/philength': '経度の長さ',
			'sidebar/geometry/sphere_geometry/thetastart': '緯度の開始点',
			'sidebar/geometry/sphere_geometry/thetalength': '緯度の長さ',

			'sidebar/geometry/torus_geometry/radius': '半径',
			'sidebar/geometry/torus_geometry/tube': '管の厚さ',
			'sidebar/geometry/torus_geometry/radialsegments': '半径分割',
			'sidebar/geometry/torus_geometry/tubularsegments': '管の分割',
			'sidebar/geometry/torus_geometry/arc': '弧度',

			'sidebar/geometry/torusKnot_geometry/radius': '半径',
			'sidebar/geometry/torusKnot_geometry/tube': '管の厚さ',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': '管の分割',
			'sidebar/geometry/torusKnot_geometry/radialsegments': '半径分割',
			'sidebar/geometry/torusKnot_geometry/p': '管の曲率',
			'sidebar/geometry/torusKnot_geometry/q': 'ねじれの角度',

			'sidebar/geometry/tube_geometry/path': 'パス',
			'sidebar/geometry/tube_geometry/radius': '半径',
			'sidebar/geometry/tube_geometry/tube': '管の厚さ',
			'sidebar/geometry/tube_geometry/tubularsegments': '管の分割',
			'sidebar/geometry/tube_geometry/radialsegments': '半径分割',
			'sidebar/geometry/tube_geometry/closed': '閉じる',
			'sidebar/geometry/tube_geometry/curvetype': '曲線タイプ',
			'sidebar/geometry/tube_geometry/tension': '張力',

			'sidebar/material/new': '更新',
			'sidebar/material/copy': 'コピー',
			'sidebar/material/paste': '貼り付け',
			'sidebar/material/slot': 'スロット',
			'sidebar/material/type': 'タイプ',
			'sidebar/material/uuid': '識別子',
			'sidebar/material/name': '名前',
			'sidebar/material/program': 'プログラム',
			'sidebar/material/info': '情報',
			'sidebar/material/vertex': '頂点',
			'sidebar/material/fragment': 'フラグメント',
			'sidebar/material/color': '色',
			'sidebar/material/depthPacking': '深度パッキング',
			'sidebar/material/roughness': '粗さ',
			'sidebar/material/metalness': '金属性',
			'sidebar/material/reflectivity': '反射率',
			'sidebar/material/emissive': '発光',
			'sidebar/material/specular': '鏡面反射',
			'sidebar/material/shininess': '光沢',
			'sidebar/material/clearcoat': 'クリアコート',
			'sidebar/material/clearcoatroughness': 'クリアコートの粗さ',
			'sidebar/material/transmission': '透過',
			'sidebar/material/attenuationDistance': '減衰距離',
			'sidebar/material/attenuationColor': '減衰色',
			'sidebar/material/thickness': '厚さ',
			'sidebar/material/vertexcolors': '頂点色',
			'sidebar/material/matcap': 'マテリアルキャプチャ',
			'sidebar/material/map': 'テクスチャ',
			'sidebar/material/alphamap': 'アルファマップ',
			'sidebar/material/bumpmap': 'バンプマップ',
			'sidebar/material/normalmap': '法線マップ',
			'sidebar/material/clearcoatnormalmap': 'クリアコート法線マップ',
			'sidebar/material/displacementmap': '変位マップ',
			'sidebar/material/roughnessmap': '粗さマップ',
			'sidebar/material/metalnessmap': '金属性マップ',
			'sidebar/material/specularmap': '鏡面反射マップ',
			'sidebar/material/envmap': '環境マップ',
			'sidebar/material/lightmap': 'ライトマップ',
			'sidebar/material/aomap': 'AOマップ',
			'sidebar/material/emissivemap': '発光マップ',
			'sidebar/material/gradientmap': 'グラデーションマップ',
			'sidebar/material/side': '面',
			'sidebar/material/size': 'サイズ',
			'sidebar/material/sizeAttenuation': 'サイズ減衰',
			'sidebar/material/flatShading': 'フラットシェーディング',
			'sidebar/material/blending': 'ブレンド',
			'sidebar/material/opacity': '透明度',
			'sidebar/material/transparent': '透明性',
			'sidebar/material/alphatest': 'アルファテスト',
			'sidebar/material/depthtest': '深度テスト',
			'sidebar/material/depthwrite': '深度バッファ',
			'sidebar/material/wireframe': 'ワイヤーフレーム',
			'sidebar/material/userdata': 'ユーザーデータ',

			'sidebar/script': 'スクリプト',
			'sidebar/script/new': '新規作成',
			'sidebar/script/edit': '編集',
			'sidebar/script/remove': '削除',

			'sidebar/project': 'プロジェクト',
			'sidebar/project/title': 'タイトル',
			'sidebar/project/editable': '編集可能',
			'sidebar/project/vr': 'バーチャルリアル',
			'sidebar/project/renderer': 'レンダラー',
			'sidebar/project/antialias': 'アンチエイリアス',
			'sidebar/project/shadows': '影',
			'sidebar/project/physicallyCorrectLights': '物理的正確な光源',
			'sidebar/project/toneMapping': 'トーンマッピング',
			'sidebar/project/materials': 'マテリアル',
			'sidebar/project/Assign': '適用',

			'sidebar/project/video': 'ビデオ',
			'sidebar/project/resolution': '解像度',
			'sidebar/project/duration': '時間',
			'sidebar/project/render': 'レンダリング',

			'sidebar/settings': '設定',
			'sidebar/settings/language': '言語',

			'sidebar/settings/shortcuts': 'ショートカット',
			'sidebar/settings/shortcuts/translate': '移動',
			'sidebar/settings/shortcuts/rotate': '回転',
			'sidebar/settings/shortcuts/scale': 'スケール',
			'sidebar/settings/shortcuts/undo': '元に戻す',
			'sidebar/settings/shortcuts/focus': 'フォーカス',
			'sidebar/settings/shortcuts/save': '保存',

			'sidebar/settings/viewport': 'ビューポート',
			'sidebar/settings/viewport/grid': 'グリッド',
			'sidebar/settings/viewport/ground': '地面',
			'sidebar/settings/viewport/helpers': 'ヘルパー',

			'sidebar/history': '履歴',
			'sidebar/history/persistent': 'ローカルストレージ',

			'toolbar/translate': '移動',
			'toolbar/rotate': '回転',
			'toolbar/scale': 'スケール',
			'toolbar/local': 'ローカル',

			'viewport/info/objects': 'オブジェクト',
			'viewport/info/vertices': '頂点',
			'viewport/info/triangles': '三角形',
			'viewport/info/frametime': 'フレーム時間',

			// --- MRPP MODIFICATION START ---
			...mrppStrings["ja-jp"],
			// --- MRPP MODIFICATION END ---
		},

		"zh-tw": {
			"menubar/file": "檔案",
			"menubar/file/new": "新增",
			"menubar/file/import": "匯入",
			"menubar/file/save": "儲存",
			"menubar/file/export/geometry": "匯出幾何體",
			"menubar/file/export/object": "匯出物件",
			"menubar/file/export/scene": "匯出場景",
			"menubar/file/export/dae": "匯出DAE",
			"menubar/file/export/drc": "匯出DRC",
			"menubar/file/export/glb": "匯出GLB",
			"menubar/file/export/gltf": "匯出GLTF",
			"menubar/file/export/obj": "匯出OBJ",
			"menubar/file/export/ply": "匯出PLY",
			"menubar/file/export/ply_binary": "匯出PLY(二進位)",
			"menubar/file/export/stl": "匯出STL",
			"menubar/file/export/stl_binary": "匯出STL(二進位)",
			"menubar/file/export/usdz": "匯出USDZ",
			"menubar/file/publish": "發佈",

			"menubar/edit": "編輯",
			"menubar/edit/undo": "復原 (Ctrl+Z)",
			"menubar/edit/redo": "重做 (Ctrl+Shift+Z)",
			"menubar/edit/clear_history": "清除歷史記錄",
			"menubar/edit/center": "置中",
			"menubar/edit/clone": "複製",
			"menubar/edit/delete": "刪除 (Del)",
			"menubar/edit/fixcolormaps": "修復顏色貼圖",

			"menubar/add": "新增",
			"menubar/add/group": "群組",
			"menubar/add/plane": "平面",
			"menubar/add/box": "立方體",
			"menubar/add/capsule": "膠囊體",
			"menubar/add/circle": "圓形",
			"menubar/add/cylinder": "圓柱體",
			"menubar/add/ring": "環形",
			"menubar/add/sphere": "球體",
			"menubar/add/dodecahedron": "十二面體",
			"menubar/add/icosahedron": "二十面體",
			"menubar/add/octahedron": "八面體",
			"menubar/add/tetrahedron": "四面體",
			"menubar/add/torus": "環形體",
			"menubar/add/torusknot": "環面紐結體",
			"menubar/add/tube": "管狀體",
			"menubar/add/lathe": "旋轉體",
			"menubar/add/sprite": "精靈",
			"menubar/add/pointlight": "點光源",
			"menubar/add/spotlight": "聚光燈",
			"menubar/add/directionallight": "平行光",
			"menubar/add/hemispherelight": "半球光",
			"menubar/add/ambientlight": "環境光",
			"menubar/add/perspectivecamera": "透視攝影機",
			"menubar/add/orthographiccamera": "正交攝影機",


			"menubar/status/autosave": "自動儲存",

			"menubar/play": "啟動",
			"menubar/play/stop": "暫停",
			"menubar/play/play": "啟動",

			"menubar/examples": "範例",
			"menubar/examples/Arkanoid": "打磚塊",
			"menubar/examples/Camera": "攝影機",
			"menubar/examples/Particles": "粒子",
			"menubar/examples/Pong": "乒乓球",
			"menubar/examples/Shaders": "著色器",

			"menubar/view": "檢視",
			"menubar/view/fullscreen": "全螢幕",

			"menubar/help": "說明",
			"menubar/help/source_code": "原始碼",
			"menubar/help/icons": "圖示元件包",
			"menubar/help/about": "關於",
			"menubar/help/manual": "手冊",


			"sidebar/scene": "場景",
			"sidebar/scene/background": "背景",
			"sidebar/scene/environment": "環境",
			"sidebar/scene/fog": "霧",

			"sidebar/properties/object": "屬性",
			"sidebar/properties/geometry": "幾何元件",
			"sidebar/properties/material": "材質元件",
			"sidebar/properties/script": "指令碼",

			"sidebar/object/type": "類型",
			"sidebar/object/type_value/scene": "場景",
			"sidebar/object/type_value/group": "群組",
			"sidebar/object/type_value/object3d": "物件",
			"sidebar/object/type_value/mesh": "網格",
			"sidebar/object/type_value/line": "線",
			"sidebar/object/type_value/linesegments": "線段",
			"sidebar/object/type_value/points": "點集",
			"sidebar/object/type_value/sprite": "精靈",
			"sidebar/object/type_value/camera": "相機",
			"sidebar/object/type_value/perspectivecamera": "透視相機",
			"sidebar/object/type_value/orthographiccamera": "正交相機",
			"sidebar/object/type_value/light": "燈光",
			"sidebar/object/type_value/ambientlight": "環境光",
			"sidebar/object/type_value/directionallight": "平行光",
			"sidebar/object/type_value/hemispherelight": "半球光",
			"sidebar/object/type_value/pointlight": "點光源",
			"sidebar/object/type_value/spotlight": "聚光燈",
			"sidebar/object/new": "更新",
			"sidebar/object/uuid": "識別碼",
			"sidebar/object/name": "名稱",
			"sidebar/object/position": "位置",
			"sidebar/object/rotation": "旋轉",
			"sidebar/object/scale": "縮放",
			"sidebar/object/fov": "視野",
			"sidebar/object/left": "左",
			"sidebar/object/right": "右",
			"sidebar/object/top": "上",
			"sidebar/object/bottom": "下",
			"sidebar/object/near": "近點",
			"sidebar/object/far": "遠點",
			"sidebar/object/intensity": "強度",
			"sidebar/object/color": "顏色",
			"sidebar/object/groundcolor": "基色",
			"sidebar/object/distance": "距離",
			"sidebar/object/angle": "角度",
			"sidebar/object/penumbra": "邊緣",
			"sidebar/object/decay": "衰減",
			"sidebar/object/shadow": "陰影",
			"sidebar/object/shadowBias": "陰影偏移",
			"sidebar/object/shadowNormalBias": "陰影法線偏移",
			"sidebar/object/shadowRadius": "陰影半徑",
			"sidebar/object/cast": "產生",
			"sidebar/object/receive": "接受",
			"sidebar/object/visible": "可見性",
			"sidebar/object/frustumcull": "視錐體裁切",
			"sidebar/object/renderorder": "渲染次序",
			"sidebar/object/userdata": "自訂資料",


			"sidebar/geometry/type": "類型",
			"sidebar/geometry/new": "更新",
			"sidebar/geometry/uuid": "識別碼",
			"sidebar/geometry/name": "名稱",
			"sidebar/geometry/bounds": "邊界",
			"sidebar/geometry/show_vertex_normals": "顯示頂點法線",

			"sidebar/geometry/box_geometry/width": "寬度",
			"sidebar/geometry/box_geometry/height": "高度",
			"sidebar/geometry/box_geometry/depth": "深度",
			"sidebar/geometry/box_geometry/widthseg": "寬度分段",
			"sidebar/geometry/box_geometry/heightseg": "高度分段",
			"sidebar/geometry/box_geometry/depthseg": "深度分段",

			"sidebar/geometry/buffer_geometry/attributes": "屬性",
			"sidebar/geometry/buffer_geometry/index": "索引",

			"sidebar/geometry/capsule_geometry/radius": "半徑",
			"sidebar/geometry/capsule_geometry/length": "長度",
			"sidebar/geometry/capsule_geometry/capseg": "膠囊分段",
			"sidebar/geometry/capsule_geometry/radialseg": "半徑分段",

			"sidebar/geometry/circle_geometry/radius": "半徑",
			"sidebar/geometry/circle_geometry/segments": "分段",
			"sidebar/geometry/circle_geometry/thetastart": "弧度起點",
			"sidebar/geometry/circle_geometry/thetalength": "弧度長度",

			"sidebar/geometry/cylinder_geometry/radiustop": "頂部半徑",
			"sidebar/geometry/cylinder_geometry/radiusbottom": "底部半徑",
			"sidebar/geometry/cylinder_geometry/height": "高度",
			"sidebar/geometry/cylinder_geometry/radialsegments": "徑向分段",
			"sidebar/geometry/cylinder_geometry/heightsegments": "高度分段",
			"sidebar/geometry/cylinder_geometry/openended": "開端",

			"sidebar/geometry/extrude_geometry/curveSegments": "曲線段",
			"sidebar/geometry/extrude_geometry/steps": "細分點數",
			"sidebar/geometry/extrude_geometry/depth": "深度",
			"sidebar/geometry/extrude_geometry/bevelEnabled": "啟用斜角",
			"sidebar/geometry/extrude_geometry/bevelThickness": "斜角厚度",
			"sidebar/geometry/extrude_geometry/bevelSize": "斜角大小",
			"sidebar/geometry/extrude_geometry/bevelOffset": "斜角偏移量",
			"sidebar/geometry/extrude_geometry/bevelSegments": "斜角分段",
			"sidebar/geometry/extrude_geometry/shape": "轉換圖形",

			"sidebar/geometry/dodecahedron_geometry/radius": "半徑",
			"sidebar/geometry/dodecahedron_geometry/detail": "面片分段",

			"sidebar/geometry/icosahedron_geometry/radius": "半徑",
			"sidebar/geometry/icosahedron_geometry/detail": "面片分段",

			"sidebar/geometry/octahedron_geometry/radius": "半徑",
			"sidebar/geometry/octahedron_geometry/detail": "面片分段",

			"sidebar/geometry/tetrahedron_geometry/radius": "半徑",
			"sidebar/geometry/tetrahedron_geometry/detail": "面片分段",

			"sidebar/geometry/lathe_geometry/segments": "分段",
			"sidebar/geometry/lathe_geometry/phistart": "經度起點",
			"sidebar/geometry/lathe_geometry/philength": "經度長度",
			"sidebar/geometry/lathe_geometry/points": "點",

			"sidebar/geometry/plane_geometry/width": "寬度",
			"sidebar/geometry/plane_geometry/height": "長度",
			"sidebar/geometry/plane_geometry/widthsegments": "寬度分段",
			"sidebar/geometry/plane_geometry/heightsegments": "長度分段",

			"sidebar/geometry/ring_geometry/innerRadius": "內半徑",
			"sidebar/geometry/ring_geometry/outerRadius": "外半徑",
			"sidebar/geometry/ring_geometry/thetaSegments": "弧度分段",
			"sidebar/geometry/ring_geometry/phiSegments": "經度分段",
			"sidebar/geometry/ring_geometry/thetastart": "弧度起點",
			"sidebar/geometry/ring_geometry/thetalength": "弧度長度",

			"sidebar/geometry/shape_geometry/curveSegments": "曲線段",
			"sidebar/geometry/shape_geometry/extrude": "拉伸",

			"sidebar/geometry/sphere_geometry/radius": "半徑",
			"sidebar/geometry/sphere_geometry/widthsegments": "寬度分段",
			"sidebar/geometry/sphere_geometry/heightsegments": "長度分段",
			"sidebar/geometry/sphere_geometry/phistart": "經度起點",
			"sidebar/geometry/sphere_geometry/philength": "經度長度",
			"sidebar/geometry/sphere_geometry/thetastart": "緯度起點",
			"sidebar/geometry/sphere_geometry/thetalength": "緯度長度",

			"sidebar/geometry/torus_geometry/radius": "半徑",
			"sidebar/geometry/torus_geometry/tube": "管厚",
			"sidebar/geometry/torus_geometry/radialsegments": "半徑分段",
			"sidebar/geometry/torus_geometry/tubularsegments": "管厚分段",
			"sidebar/geometry/torus_geometry/arc": "弧度",

			"sidebar/geometry/torusKnot_geometry/radius": "半徑",
			"sidebar/geometry/torusKnot_geometry/tube": "管厚",
			"sidebar/geometry/torusKnot_geometry/tubularsegments": "管厚分段",
			"sidebar/geometry/torusKnot_geometry/radialsegments": "半徑分段",
			"sidebar/geometry/torusKnot_geometry/p": "管長弧度",
			"sidebar/geometry/torusKnot_geometry/q": "扭曲弧度",

			"sidebar/geometry/tube_geometry/path": "路徑",
			"sidebar/geometry/tube_geometry/radius": "半徑",
			"sidebar/geometry/tube_geometry/tube": "管厚",
			"sidebar/geometry/tube_geometry/tubularsegments": "管厚分段",
			"sidebar/geometry/tube_geometry/radialsegments": "半徑分段",
			"sidebar/geometry/tube_geometry/closed": "閉合",
			"sidebar/geometry/tube_geometry/curvetype": "曲線類型",
			"sidebar/geometry/tube_geometry/tension": "張力",

			"sidebar/material/new": "更新",
			"sidebar/material/copy": "複製",
			"sidebar/material/paste": "貼上",
			"sidebar/material/slot": "插槽",
			"sidebar/material/type": "類型",
			"sidebar/material/uuid": "識別碼",
			"sidebar/material/name": "名稱",
			"sidebar/material/program": "程式",
			"sidebar/material/info": "資訊",
			"sidebar/material/vertex": "頂點",
			"sidebar/material/fragment": "片元",
			"sidebar/material/color": "顏色",
			"sidebar/material/depthPacking": "深度包裝",
			"sidebar/material/roughness": "粗糙度",
			"sidebar/material/metalness": "金屬度",
			"sidebar/material/reflectivity": "反射率",
			"sidebar/material/emissive": "自發光",
			"sidebar/material/specular": "高光",
			"sidebar/material/shininess": "高光大小",
			"sidebar/material/clearcoat": "清漆",
			"sidebar/material/clearcoatroughness": "清漆粗糙度",
			"sidebar/material/transmission": "透光",
			"sidebar/material/attenuationDistance": "衰減距離",
			"sidebar/material/attenuationColor": "衰減顏色",
			"sidebar/material/thickness": "厚度",
			"sidebar/material/vertexcolors": "頂點顏色",
			"sidebar/material/matcap": "材質捕獲",
			"sidebar/material/map": "貼圖",
			"sidebar/material/alphamap": "透明貼圖",
			"sidebar/material/bumpmap": "凹凸貼圖",
			"sidebar/material/normalmap": "法線貼圖",
			"sidebar/material/clearcoatnormalmap": "清漆法線貼圖",
			"sidebar/material/displacementmap": "置換貼圖",
			"sidebar/material/roughnessmap": "粗糙貼圖",
			"sidebar/material/metalnessmap": "金屬貼圖",
			"sidebar/material/specularmap": "高光貼圖",
			"sidebar/material/envmap": "環境貼圖",
			"sidebar/material/lightmap": "光照貼圖",
			"sidebar/material/aomap": "環境光遮蔽貼圖",
			"sidebar/material/emissivemap": "自發光貼圖",
			"sidebar/material/gradientmap": "漸變貼圖",
			"sidebar/material/side": "面",
			"sidebar/material/size": "大小",
			"sidebar/material/sizeAttenuation": "大小衰減",
			"sidebar/material/flatShading": "平面著色",
			"sidebar/material/blending": "混合",
			"sidebar/material/opacity": "透明度",
			"sidebar/material/transparent": "透明性",
			"sidebar/material/alphatest": "α測試",
			"sidebar/material/depthtest": "深度測試",
			"sidebar/material/depthwrite": "深度緩衝",
			"sidebar/material/wireframe": "線框",
			"sidebar/material/userdata": "自訂資料",

			"sidebar/script": "指令碼",
			"sidebar/script/new": "新建",
			"sidebar/script/edit": "編輯",
			"sidebar/script/remove": "刪除",

			"sidebar/project": "專案",
			"sidebar/project/title": "標題",
			"sidebar/project/editable": "可編輯性",
			"sidebar/project/vr": "虛擬實境",
			"sidebar/project/renderer": "渲染器",
			"sidebar/project/antialias": "抗鋸齒",
			"sidebar/project/shadows": "陰影",
			"sidebar/project/physicallyCorrectLights": "物理燈光",
			"sidebar/project/toneMapping": "色調映射",
			"sidebar/project/materials": "材質",
			"sidebar/project/Assign": "應用",

			"sidebar/project/video": "視訊",
			"sidebar/project/resolution": "解析度",
			"sidebar/project/duration": "時長",
			"sidebar/project/render": "渲染",

			"sidebar/settings": "設定",
			"sidebar/settings/language": "語言",

			"sidebar/settings/shortcuts": "快速鍵",
			"sidebar/settings/shortcuts/translate": "移動",
			"sidebar/settings/shortcuts/rotate": "旋轉",
			"sidebar/settings/shortcuts/scale": "縮放",
			"sidebar/settings/shortcuts/undo": "復原",
			"sidebar/settings/shortcuts/focus": "聚焦",
			"sidebar/settings/shortcuts/save": "儲存",

			"sidebar/settings/viewport": "視窗",
			"sidebar/settings/viewport/grid": "網格",
			"sidebar/settings/viewport/ground": "地面",
			"sidebar/settings/viewport/helpers": "輔助",

			"sidebar/history": "歷史記錄",
			"sidebar/history/persistent": "本機儲存",

			"toolbar/translate": "移動",
			"toolbar/rotate": "旋轉",
			"toolbar/scale": "縮放",
			"toolbar/local": "區域性",

			"viewport/info/objects": "物件",
			"viewport/info/vertices": "頂點",
			"viewport/info/triangles": "三角形",
			"viewport/info/frametime": "幀時",

			// --- MRPP MODIFICATION START ---
			...mrppStrings["zh-tw"],
			// --- MRPP MODIFICATION END ---
		},

		"th-th": {
			"menubar/file": "ไฟล์",
			"menubar/file/new": "สร้างใหม่",
			"menubar/file/import": "นำเข้า",
			"menubar/file/save": "บันทึก",
			"menubar/file/export/geometry": "ส่งออกรูปทรง",
			"menubar/file/export/object": "ส่งออกวัตถุ",
			"menubar/file/export/scene": "ส่งออกฉาก",
			"menubar/file/export/dae": "ส่งออก DAE",
			"menubar/file/export/drc": "ส่งออก DRC",
			"menubar/file/export/glb": "ส่งออก GLB",
			"menubar/file/export/gltf": "ส่งออก GLTF",
			"menubar/file/export/obj": "ส่งออก OBJ",
			"menubar/file/export/ply": "ส่งออก PLY",
			"menubar/file/export/ply_binary": "ส่งออก PLY (ไบนารี)",
			"menubar/file/export/stl": "ส่งออก STL",
			"menubar/file/export/stl_binary": "ส่งออก STL (ไบนารี)",
			"menubar/file/export/usdz": "ส่งออก USDZ",
			"menubar/file/publish": "เผยแพร่",

			"menubar/edit": "แก้ไข",
			"menubar/edit/undo": "ยกเลิก (Ctrl+Z)",
			"menubar/edit/redo": "ทำซ้ำ (Ctrl+Shift+Z)",
			"menubar/edit/clear_history": "ล้างประวัติ",
			"menubar/edit/center": "จัดกึ่งกลาง",
			"menubar/edit/clone": "คัดลอก",
			"menubar/edit/delete": "ลบ (Del)",
			"menubar/edit/fixcolormaps": "ซ่อมแผนที่สี",

			"menubar/add": "เพิ่ม",
			"menubar/add/group": "กลุ่ม",
			"menubar/add/plane": "ระนาบ",
			"menubar/add/box": "ลูกเต๋า",
			"menubar/add/capsule": "แคปซูล",
			"menubar/add/circle": "วงกลม",
			"menubar/add/cylinder": "ทรงกระบอก",
			"menubar/add/ring": "วงแหวน",
			"menubar/add/sphere": "ทรงกลม",
			"menubar/add/dodecahedron": "ทรงสิบสองหน้า",
			"menubar/add/icosahedron": "ทรงยี่สิบหน้า",
			"menubar/add/octahedron": "ทรงแปดหน้า",
			"menubar/add/tetrahedron": "ทรงสี่หน้า",
			"menubar/add/torus": "ทอรัส",
			"menubar/add/torusknot": "ทอรัสนอต",
			"menubar/add/tube": "ท่อ",
			"menubar/add/lathe": "เครื่องกลึง",
			"menubar/add/sprite": "สไปรต์",
			"menubar/add/pointlight": "แสงจุด",
			"menubar/add/spotlight": "แสงสปอต",
			"menubar/add/directionallight": "แสงทิศทาง",
			"menubar/add/hemispherelight": "แสงซีกโลก",
			"menubar/add/ambientlight": "แสงแวดล้อม",
			"menubar/add/perspectivecamera": "กล้องมุมมอง",
			"menubar/add/orthographiccamera": "กล้องออโธกราฟิก",


			"menubar/status/autosave": "บันทึกอัตโนมัติ",

			"menubar/play": "เริ่ม",
			"menubar/play/stop": "หยุดชั่วคราว",
			"menubar/play/play": "เริ่ม",

			"menubar/examples": "ตัวอย่าง",
			"menubar/examples/Arkanoid": "ตีอิฐ",
			"menubar/examples/Camera": "กล้อง",
			"menubar/examples/Particles": "อนุภาค",
			"menubar/examples/Pong": "ปิงปอง",
			"menubar/examples/Shaders": "เชดเดอร์",

			"menubar/view": "มุมมอง",
			"menubar/view/fullscreen": "เต็มหน้าจอ",

			"menubar/help": "ช่วยเหลือ",
			"menubar/help/source_code": "ซอร์สโค้ด",
			"menubar/help/icons": "ชุดไอคอนคอมโพเนนต์",
			"menubar/help/about": "เกี่ยวกับ",
			"menubar/help/manual": "คู่มือ",


			"sidebar/scene": "ฉาก",
			"sidebar/scene/background": "พื้นหลัง",
			"sidebar/scene/environment": "สิ่งแวดล้อม",
			"sidebar/scene/fog": "หมอก",

			"sidebar/properties/object": "คุณสมบัติ",
			"sidebar/properties/geometry": "คอมโพเนนต์เรขาคณิต",
			"sidebar/properties/material": "คอมโพเนนต์วัสดุ",
			"sidebar/properties/script": "สคริปต์",

			"sidebar/object/type": "ประเภท",
			"sidebar/object/type_value/scene": "ฉาก",
			"sidebar/object/type_value/group": "กลุ่ม",
			"sidebar/object/type_value/object3d": "วัตถุ",
			"sidebar/object/type_value/mesh": "เมช",
			"sidebar/object/type_value/line": "เส้น",
			"sidebar/object/type_value/linesegments": "ชุดเส้น",
			"sidebar/object/type_value/points": "ชุดจุด",
			"sidebar/object/type_value/sprite": "สไปรต์",
			"sidebar/object/type_value/camera": "กล้อง",
			"sidebar/object/type_value/perspectivecamera": "กล้องมุมมองภาพ",
			"sidebar/object/type_value/orthographiccamera": "กล้องออร์โธกราฟิก",
			"sidebar/object/type_value/light": "แสง",
			"sidebar/object/type_value/ambientlight": "แสงแวดล้อม",
			"sidebar/object/type_value/directionallight": "แสงทิศทาง",
			"sidebar/object/type_value/hemispherelight": "แสงครึ่งทรงกลม",
			"sidebar/object/type_value/pointlight": "แสงจุด",
			"sidebar/object/type_value/spotlight": "สปอตไลต์",
			"sidebar/object/new": "อัปเดต",
			"sidebar/object/uuid": "รหัสประจำตัว",
			"sidebar/object/name": "ชื่อ",
			"sidebar/object/position": "ตำแหน่ง",
			"sidebar/object/rotation": "การหมุน",
			"sidebar/object/scale": "สเกล",
			"sidebar/object/fov": "มุมมอง",
			"sidebar/object/left": "ซ้าย",
			"sidebar/object/right": "ขวา",
			"sidebar/object/top": "บน",
			"sidebar/object/bottom": "ล่าง",
			"sidebar/object/near": "ใกล้",
			"sidebar/object/far": "ไกล",
			"sidebar/object/intensity": "ความเข้ม",
			"sidebar/object/color": "สี",
			"sidebar/object/groundcolor": "สีพื้น",
			"sidebar/object/distance": "ระยะทาง",
			"sidebar/object/angle": "มุม",
			"sidebar/object/penumbra": "ขอบ",
			"sidebar/object/decay": "การลดลง",
			"sidebar/object/shadow": "เงา",
			"sidebar/object/shadowBias": "อคติเงา",
			"sidebar/object/shadowNormalBias": "อคติเงาปกติ",
			"sidebar/object/shadowRadius": "รัศมีเงา",
			"sidebar/object/cast": "สร้าง",
			"sidebar/object/receive": "รับ",
			"sidebar/object/visible": "การมองเห็น",
			"sidebar/object/frustumcull": "ตัดเฟรัสตัม",
			"sidebar/object/renderorder": "ลำดับการเรนเดอร์",
			"sidebar/object/userdata": "ข้อมูลที่กำหนดเอง",


			"sidebar/geometry/type": "ประเภท",
			"sidebar/geometry/new": "อัปเดต",
			"sidebar/geometry/uuid": "รหัสประจำตัว",
			"sidebar/geometry/name": "ชื่อ",
			"sidebar/geometry/bounds": "ขอบเขต",
			"sidebar/geometry/show_vertex_normals": "แสดงเส้นปกติจุดยอด",

			"sidebar/geometry/box_geometry/width": "ความกว้าง",
			"sidebar/geometry/box_geometry/height": "ความสูง",
			"sidebar/geometry/box_geometry/depth": "ความลึก",
			"sidebar/geometry/box_geometry/widthseg": "เซกเมนต์ความกว้าง",
			"sidebar/geometry/box_geometry/heightseg": "เซกเมนต์ความสูง",
			"sidebar/geometry/box_geometry/depthseg": "เซกเมนต์ความลึก",

			"sidebar/geometry/buffer_geometry/attributes": "แอตทริบิวต์",
			"sidebar/geometry/buffer_geometry/index": "ดัชนี",

			"sidebar/geometry/capsule_geometry/radius": "รัศมี",
			"sidebar/geometry/capsule_geometry/length": "ความยาว",
			"sidebar/geometry/capsule_geometry/capseg": "เซกเมนต์แคปซูล",
			"sidebar/geometry/capsule_geometry/radialseg": "เซกเมนต์รัศมี",

			"sidebar/geometry/circle_geometry/radius": "รัศมี",
			"sidebar/geometry/circle_geometry/segments": "เซกเมนต์",
			"sidebar/geometry/circle_geometry/thetastart": "จุดเริ่มต้นเรเดียน",
			"sidebar/geometry/circle_geometry/thetalength": "ความยาวเรเดียน",

			"sidebar/geometry/cylinder_geometry/radiustop": "รัศมีด้านบน",
			"sidebar/geometry/cylinder_geometry/radiusbottom": "รัศมีด้านล่าง",
			"sidebar/geometry/cylinder_geometry/height": "ความสูง",
			"sidebar/geometry/cylinder_geometry/radialsegments": "เซกเมนต์รัศมี",
			"sidebar/geometry/cylinder_geometry/heightsegments": "เซกเมนต์ความสูง",
			"sidebar/geometry/cylinder_geometry/openended": "ปลายเปิด",

			"sidebar/geometry/extrude_geometry/curveSegments": "เซกเมนต์เส้นโค้ง",
			"sidebar/geometry/extrude_geometry/steps": "จำนวนจุดย่อย",
			"sidebar/geometry/extrude_geometry/depth": "ความลึก",
			"sidebar/geometry/extrude_geometry/bevelEnabled": "เปิดใช้งานมุมเอียง",
			"sidebar/geometry/extrude_geometry/bevelThickness": "ความหนามุมเอียง",
			"sidebar/geometry/extrude_geometry/bevelSize": "ขนาดมุมเอียง",
			"sidebar/geometry/extrude_geometry/bevelOffset": "ออฟเซ็ตมุมเอียง",
			"sidebar/geometry/extrude_geometry/bevelSegments": "เซกเมนต์มุมเอียง",
			"sidebar/geometry/extrude_geometry/shape": "แปลงรูปทรง",

			"sidebar/geometry/dodecahedron_geometry/radius": "รัศมี",
			"sidebar/geometry/dodecahedron_geometry/detail": "เซกเมนต์หน้า",

			"sidebar/geometry/icosahedron_geometry/radius": "รัศมี",
			"sidebar/geometry/icosahedron_geometry/detail": "เซกเมนต์หน้า",

			"sidebar/geometry/octahedron_geometry/radius": "รัศมี",
			"sidebar/geometry/octahedron_geometry/detail": "เซกเมนต์หน้า",

			"sidebar/geometry/tetrahedron_geometry/radius": "รัศมี",
			"sidebar/geometry/tetrahedron_geometry/detail": "เซกเมนต์หน้า",

			"sidebar/geometry/lathe_geometry/segments": "เซกเมนต์",
			"sidebar/geometry/lathe_geometry/phistart": "จุดเริ่มต้นลองจิจูด",
			"sidebar/geometry/lathe_geometry/philength": "ความยาวลองจิจูด",
			"sidebar/geometry/lathe_geometry/points": "จุด",

			"sidebar/geometry/plane_geometry/width": "ความกว้าง",
			"sidebar/geometry/plane_geometry/height": "ความยาว",
			"sidebar/geometry/plane_geometry/widthsegments": "เซกเมนต์ความกว้าง",
			"sidebar/geometry/plane_geometry/heightsegments": "เซกเมนต์ความยาว",

			"sidebar/geometry/ring_geometry/innerRadius": "รัศมีใน",
			"sidebar/geometry/ring_geometry/outerRadius": "รัศมีนอก",
			"sidebar/geometry/ring_geometry/thetaSegments": "เซกเมนต์เรเดียน",
			"sidebar/geometry/ring_geometry/phiSegments": "เซกเมนต์ลองจิจูด",
			"sidebar/geometry/ring_geometry/thetastart": "จุดเริ่มต้นเรเดียน",
			"sidebar/geometry/ring_geometry/thetalength": "ความยาวเรเดียน",

			"sidebar/geometry/shape_geometry/curveSegments": "เซกเมนต์เส้นโค้ง",
			"sidebar/geometry/shape_geometry/extrude": "ยึด",

			"sidebar/geometry/sphere_geometry/radius": "รัศมี",
			"sidebar/geometry/sphere_geometry/widthsegments": "เซกเมนต์ความกว้าง",
			"sidebar/geometry/sphere_geometry/heightsegments": "เซกเมนต์ความยาว",
			"sidebar/geometry/sphere_geometry/phistart": "จุดเริ่มต้นลองจิจูด",
			"sidebar/geometry/sphere_geometry/philength": "ความยาวลองจิจูด",
			"sidebar/geometry/sphere_geometry/thetastart": "จุดเริ่มต้นละติจูด",
			"sidebar/geometry/sphere_geometry/thetalength": "ความยาวละติจูด",

			"sidebar/geometry/torus_geometry/radius": "รัศมี",
			"sidebar/geometry/torus_geometry/tube": "ความหนาท่อ",
			"sidebar/geometry/torus_geometry/radialsegments": "เซกเมนต์รัศมี",
			"sidebar/geometry/torus_geometry/tubularsegments": "เซกเมนต์ความหนาท่อ",
			"sidebar/geometry/torus_geometry/arc": "เรเดียน",

			"sidebar/geometry/torusKnot_geometry/radius": "รัศมี",
			"sidebar/geometry/torusKnot_geometry/tube": "ความหนาท่อ",
			"sidebar/geometry/torusKnot_geometry/tubularsegments": "เซกเมนต์ความหนาท่อ",
			"sidebar/geometry/torusKnot_geometry/radialsegments": "เซกเมนต์รัศมี",
			"sidebar/geometry/torusKnot_geometry/p": "เรเดียนความยาวท่อ",
			"sidebar/geometry/torusKnot_geometry/q": "เรเดียนบิด",

			"sidebar/geometry/tube_geometry/path": "เส้นทาง",
			"sidebar/geometry/tube_geometry/radius": "รัศมี",
			"sidebar/geometry/tube_geometry/tube": "ความหนาท่อ",
			"sidebar/geometry/tube_geometry/tubularsegments": "เซกเมนต์ความหนาท่อ",
			"sidebar/geometry/tube_geometry/radialsegments": "เซกเมนต์รัศมี",
			"sidebar/geometry/tube_geometry/closed": "ปิด",
			"sidebar/geometry/tube_geometry/curvetype": "ประเภทเส้นโค้ง",
			"sidebar/geometry/tube_geometry/tension": "แรงตึง",

			"sidebar/material/new": "อัปเดต",
			"sidebar/material/copy": "คัดลอก",
			"sidebar/material/paste": "วาง",
			"sidebar/material/slot": "สล็อต",
			"sidebar/material/type": "ประเภท",
			"sidebar/material/uuid": "รหัสประจำตัว",
			"sidebar/material/name": "ชื่อ",
			"sidebar/material/program": "โปรแกรม",
			"sidebar/material/info": "ข้อมูล",
			"sidebar/material/vertex": "เวอร์เทกซ์",
			"sidebar/material/fragment": "เฟรกเมนต์",
			"sidebar/material/color": "สี",
			"sidebar/material/depthPacking": "การแพ็คความลึก",
			"sidebar/material/roughness": "ความขรุขระ",
			"sidebar/material/metalness": "ความเป็นโลหะ",
			"sidebar/material/reflectivity": "การสะท้อน",
			"sidebar/material/emissive": "การเปล่งแสง",
			"sidebar/material/specular": "สะท้อนแสง",
			"sidebar/material/shininess": "ขนาดการสะท้อนแสง",
			"sidebar/material/clearcoat": "เคลือบใส",
			"sidebar/material/clearcoatroughness": "ความขรุขระเคลือบใส",
			"sidebar/material/transmission": "การส่งผ่านแสง",
			"sidebar/material/attenuationDistance": "ระยะทางลดทอน",
			"sidebar/material/attenuationColor": "สีลดทอน",
			"sidebar/material/thickness": "ความหนา",
			"sidebar/material/vertexcolors": "สีจุดยอด",
			"sidebar/material/matcap": "การจับวัสดุ",
			"sidebar/material/map": "แผนที่",
			"sidebar/material/alphamap": "แผนที่โปร่งใส",
			"sidebar/material/bumpmap": "แผนที่凹凸",
			"sidebar/material/normalmap": "แผนที่ปกติ",
			"sidebar/material/clearcoatnormalmap": "แผนที่ปกติเคลือบใส",
			"sidebar/material/displacementmap": "แผนที่การกระจัด",
			"sidebar/material/roughnessmap": "แผนที่ความขรุขระ",
			"sidebar/material/metalnessmap": "แผนที่ความเป็นโลหะ",
			"sidebar/material/specularmap": "แผนที่สะท้อนแสง",
			"sidebar/material/envmap": "แผนที่สภาพแวดล้อม",
			"sidebar/material/lightmap": "แผนที่แสง",
			"sidebar/material/aomap": "แผนที่การบดบังแสงแวดล้อม",
			"sidebar/material/emissivemap": "แผนที่การเปล่งแสง",
			"sidebar/material/gradientmap": "แผนที่ไล่ระดับสี",
			"sidebar/material/side": "ด้าน",
			"sidebar/material/size": "ขนาด",
			"sidebar/material/sizeAttenuation": "การลดขนาด",
			"sidebar/material/flatShading": "การแรเงาแบบแบน",
			"sidebar/material/blending": "การผสม",
			"sidebar/material/opacity": "ความทึบ",
			"sidebar/material/transparent": "ความโปร่งใส",
			"sidebar/material/alphatest": "การทดสอบแอลฟา",
			"sidebar/material/depthtest": "การทดสอบความลึก",
			"sidebar/material/depthwrite": "บัฟเฟอร์ความลึก",
			"sidebar/material/wireframe": "โครงลวด",
			"sidebar/material/userdata": "ข้อมูลที่กำหนดเอง",

			"sidebar/script": "สคริปต์",
			"sidebar/script/new": "สร้างใหม่",
			"sidebar/script/edit": "แก้ไข",
			"sidebar/script/remove": "ลบ",

			"sidebar/project": "โครงการ",
			"sidebar/project/title": "หัวข้อ",
			"sidebar/project/editable": "ความสามารถในการแก้ไข",
			"sidebar/project/vr": "ความจริงเสมือน",
			"sidebar/project/renderer": "ตัวเรนเดอร์",
			"sidebar/project/antialias": "ป้องกันขรุขระ",
			"sidebar/project/shadows": "เงา",
			"sidebar/project/physicallyCorrectLights": "แสงทางกายภาพ",
			"sidebar/project/toneMapping": "การแมปโทน",
			"sidebar/project/materials": "วัสดุ",
			"sidebar/project/Assign": "นำไปใช้",

			"sidebar/project/video": "วิดีโอ",
			"sidebar/project/resolution": "ความละเอียด",
			"sidebar/project/duration": "ระยะเวลา",
			"sidebar/project/render": "เรนเดอร์",

			"sidebar/settings": "การตั้งค่า",
			"sidebar/settings/language": "ภาษา",

			"sidebar/settings/shortcuts": "คีย์ลัด",
			"sidebar/settings/shortcuts/translate": "เคลื่อนย้าย",
			"sidebar/settings/shortcuts/rotate": "หมุน",
			"sidebar/settings/shortcuts/scale": "ปรับสเกล",
			"sidebar/settings/shortcuts/undo": "ยกเลิก",
			"sidebar/settings/shortcuts/focus": "โฟกัส",
			"sidebar/settings/shortcuts/save": "บันทึก",

			"sidebar/settings/viewport": "วิวพอร์ต",
			"sidebar/settings/viewport/grid": "กริด",
			"sidebar/settings/viewport/ground": "พื้น",
			"sidebar/settings/viewport/helpers": "ตัวช่วย",

			"sidebar/history": "ประวัติ",
			"sidebar/history/persistent": "ที่เก็บข้อมูลท้องถิ่น",

			"toolbar/translate": "เคลื่อนย้าย",
			"toolbar/rotate": "หมุน",
			"toolbar/scale": "ปรับสเกล",
			"toolbar/local": "ท้องถิ่น",

			"viewport/info/objects": "วัตถุ",
			"viewport/info/vertices": "จุดยอด",
			"viewport/info/triangles": "สามเหลี่ยม",
			"viewport/info/frametime": "เวลาเฟรม",

			// --- MRPP MODIFICATION START ---
			...mrppStrings["th-th"],
			// --- MRPP MODIFICATION END ---
		},
	};

	return {
		getKey: function (key) {
			return values[language][key] || '???';

		}
	};

}

export { Strings };
