export { AddObjectCommand } from './AddObjectCommand.js';
export { AddScriptCommand } from './AddScriptCommand.js';
export { MoveObjectCommand } from './MoveObjectCommand.js';
export { MultiCmdsCommand } from './MultiCmdsCommand.js';
export { RemoveObjectCommand } from './RemoveObjectCommand.js';
export { RemoveScriptCommand } from './RemoveScriptCommand.js';
export { SetColorCommand } from './SetColorCommand.js';
export { SetGeometryCommand } from './SetGeometryCommand.js';
export { SetGeometryValueCommand } from './SetGeometryValueCommand.js';
export { SetMaterialColorCommand } from './SetMaterialColorCommand.js';
export { SetMaterialCommand } from './SetMaterialCommand.js';
export { SetMaterialMapCommand } from './SetMaterialMapCommand.js';
export { SetMaterialRangeCommand } from './SetMaterialRangeCommand.js';
export { SetMaterialValueCommand } from './SetMaterialValueCommand.js';
export { SetMaterialVectorCommand } from './SetMaterialVectorCommand.js';
export { SetPositionCommand } from './SetPositionCommand.js';
export { SetRotationCommand } from './SetRotationCommand.js';
export { SetScaleCommand } from './SetScaleCommand.js';
export { SetSceneCommand } from './SetSceneCommand.js';
export { SetScriptValueCommand } from './SetScriptValueCommand.js';
export { SetShadowValueCommand } from './SetShadowValueCommand.js';
export { SetUuidCommand } from './SetUuidCommand.js';
export { SetValueCommand } from './SetValueCommand.js';

// --- MRPP MODIFICATION START ---
export { AddComponentCommand } from '../../../../plugin-dist/commands/AddComponentCommand.js';
export { RemoveComponentCommand } from '../../../../plugin-dist/commands/RemoveComponentCommand.js';
export { SetComponentValueCommand } from '../../../../plugin-dist/commands/SetComponentValueCommand.js';
export { AddCommandCommand } from '../../../../plugin-dist/commands/AddCommandCommand.js';
export { RemoveCommandCommand } from '../../../../plugin-dist/commands/RemoveCommandCommand.js';
export { SetCommandValueCommand } from '../../../../plugin-dist/commands/SetCommandValueCommand.js';
export { AddEventCommand } from '../../../../plugin-dist/commands/AddEventCommand.js';
export { RemoveEventCommand } from '../../../../plugin-dist/commands/RemoveEventCommand.js';
export { SetEventValueCommand } from '../../../../plugin-dist/commands/SetEventValueCommand.js';
export { MoveMultipleObjectsCommand } from '../../../../plugin-dist/commands/MoveMultipleObjectsCommand.js';
export { MultiTransformCommand } from '../../../../plugin-dist/commands/MultiTransformCommand.js';
// --- MRPP MODIFICATION END ---
